/*
 *     Generated by class-dump 3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class NSDictionary, NSString;

@interface ConnectToService : NSObject
{
    NSString *_userVisibleName;
    NSString *_bonjourName;
    NSDictionary *_commandOptions;
    BOOL _acceptsUsername;
    BOOL _builtIn;
    NSString *_portLocation;
}

+ (id)newWithDictionary:(id)arg1;
- (id)options;
- (id)bonjourName;
- (id)userVisibleName;
- (id)portLocation;
- (BOOL)acceptsUsername;
- (BOOL)builtIn;
- (id)initWithName:(id)arg1 commandOptions:(id)arg2 bonjourName:(id)arg3 usesUser:(BOOL)arg4 portLocation:(id)arg5 builtIn:(BOOL)arg6;
- (void)dealloc;
- (id)dictionaryDescription;

@end

