/*
 *     Generated by class-dump 3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSNumber.h"

@interface NSNumber (Terminal)
- (long long)compareAsNSStringEncoding:(id)arg1;
- (long long)compareAsNSStringEncodingByUnicode:(id)arg1;
- (long long)compareAsNSStringEncodingByMacStringEncoding:(id)arg1;
- (long long)compareAsNSStringEncodingByCFStringEncoding:(id)arg1;
@end

