/*
 *     Generated by class-dump 3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSTabView.h"

@interface NSTabView (TTTabExtension)
- (struct CGRect)expandRect:(struct CGRect)arg1;
@end

