/*
 *     Generated by class-dump 3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol NSUserInterfaceItemSearching <NSObject>
- (void)searchForItemsWithSearchString:(id)arg1 resultLimit:(long long)arg2 matchedItemHandler:(id)arg3;
- (id)localizedTitlesForItem:(id)arg1;

@optional
- (void)performActionForItem:(id)arg1;
- (void)showAllHelpTopicsForSearchString:(id)arg1;
@end

