/*
 *     Generated by class-dump 3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSPanel.h"

@class RawTextView;

@interface RawTextPanel : NSPanel
{
    RawTextView *_rawTextView;
}

- (void)dealloc;
- (id)fieldEditor:(BOOL)arg1 forObject:(id)arg2;

@end

