/*
 *     Generated by class-dump 3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSNetServiceBrowserDelegate-Protocol.h"
#import "NSNetServiceDelegate-Protocol.h"
#import "NSTextFieldDelegate-Protocol.h"

@class NSArray, NSBrowser, NSButton, NSButtonCell, NSComboBox, NSMutableArray, NSMutableDictionary, NSNetService, NSNetServiceBrowser, NSPopUpButton, NSTextField, NSWindow;

@interface ServiceBrowser : NSObject <NSTextFieldDelegate, NSNetServiceDelegate, NSNetServiceBrowserDelegate>
{
    NSButtonCell *_addService;
    NSButtonCell *_removeService;
    NSButtonCell *_addServer;
    NSButtonCell *_removeServer;
    NSPopUpButton *_options;
    NSComboBox *_connectCommandLine;
    NSTextField *_usernameText;
    NSButton *_connectButton;
    NSBrowser *_serviceBrowser;
    NSWindow *_window;
    NSMutableArray *_servicesToWatch;
    NSArray *_discoveredServers;
    NSMutableArray *_updatedDiscoveredServers;
    NSMutableArray *_permanentServers;
    NSMutableDictionary *_refCountedReferences;
    NSNetServiceBrowser *_currentBrowser;
    NSNetService *_currentResolve;
    NSWindow *_addServerSheet;
    NSTextField *_newServerAddress;
    NSWindow *_addServiceSheet;
    NSTextField *_newServiceType;
    NSTextField *_newServiceName;
    NSTextField *_newServiceCommand;
    NSButton *_newServiceUsesUser;
}

+ (id)serviceBrowser;
- (id)init;
- (void)dealloc;
- (void)connect:(id)arg1;
- (void)addService:(id)arg1;
- (void)removeService:(id)arg1;
- (void)serverSheetDidEnd:(id)arg1 returnCode:(int)arg2 contextInfo:(void *)arg3;
- (void)serviceSheetDidEnd:(id)arg1 returnCode:(int)arg2 contextInfo:(void *)arg3;
- (void)sheetAddServer:(id)arg1;
- (void)sheetCancelAddServer:(id)arg1;
- (void)sheetAddService:(id)arg1;
- (void)sheetCancelAddService:(id)arg1;
- (void)addServer:(id)arg1;
- (void)removeServer:(id)arg1;
- (void)selectionChange:(id)arg1;
- (void)buildCommandLine;
- (void)controlTextDidChange:(id)arg1;
- (void)display;
- (void)addUserDefinedServices;
- (void)writeUserDefinedServices;
- (void)reloadServices;
- (int)_indexOfClosestDiscoveredServer:(id)arg1;
- (int)_indexOfMatchedDiscoveredServer:(id)arg1;
- (void)_updateScrollView;
- (long long)browser:(id)arg1 numberOfRowsInColumn:(long long)arg2;
- (void)browser:(id)arg1 willDisplayCell:(id)arg2 atRow:(long long)arg3 column:(long long)arg4;
- (void)netServiceBrowserWillSearch:(id)arg1;
- (void)netServiceBrowser:(id)arg1 didFindService:(id)arg2 moreComing:(BOOL)arg3;
- (void)netServiceBrowser:(id)arg1 didRemoveService:(id)arg2 moreComing:(BOOL)arg3;
- (void)netServiceDidResolveAddress:(id)arg1;
- (void)netService:(id)arg1 didNotResolve:(id)arg2;
- (void)windowWillClose:(id)arg1;

@end

