/*
 *     Generated by class-dump 3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "TTApplication.h"

@interface TTApplication (Scripting)
- (id)handleDoScriptCommand:(id)arg1;
- (void)handleGetURLScriptCommand:(id)arg1;
- (id)scriptSettings;
- (void)setScriptSettings:(id)arg1;
- (void)insertInScriptSettings:(id)arg1;
- (id)scriptDefaultSettings;
- (void)setScriptDefaultSettings:(id)arg1;
- (id)scriptStartupSettings;
- (void)setScriptStartupSettings:(id)arg1;
@end

