/*
 *     Generated by class-dump 3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSApplication.h"

#import "NSApplicationDelegate-Protocol.h"
#import "NSMenuDelegate-Protocol.h"
#import "NSUserInterfaceItemSearching-Protocol.h"

@class NSMenu, NSMenuItem, NSMutableArray, NSMutableDictionary, NSMutableIndexSet, NSString, NSWindow, TTWindow, TTWindowController, TTWorkspace;

@interface TTApplication : NSApplication <NSApplicationDelegate, NSMenuDelegate, NSUserInterfaceItemSearching>
{
    NSMutableIndexSet *_availableEquivalents;
    NSMutableDictionary *_windowEquivalents;
    NSMenu *_equivalentsMenu;
    NSMutableArray *_windowsToPromptForCloseArray;
    BOOL _isTerminating;
    BOOL _illegalShell;
    NSString *_defaultShell;
    NSString *_termType;
    TTWorkspace *_currentWorkspace;
    TTWindow *_mainTerminalWindow;
    TTWindowController *_mainTerminalWindowController;
    NSMenuItem *_closeWindowMenuItem;
    NSMenuItem *_closeAllMenuItem;
    NSMenuItem *_closeTabMenuItem;
    NSMenuItem *_closeOtherTabsMenuItem;
    NSMenuItem *_servicesMenuItem;
    NSMenuItem *_helpMenuItem;
    NSMenu *_newWindowMenu;
    NSMenu *_newTabMenu;
    NSMenu *_newWindowDockMenu;
    NSMenu *_dockMenu;
    NSMenu *_workspacesMenu;
    int _lowSwapSpaceWatcherKQueueFD;
    BOOL _terminateLowSwapSpaceWatcher;
    NSWindow *_lowSwapSpaceWindow;
    BOOL isInEmergencyMemoryConservationMode;
}

+ (void)initialize;
+ (struct __CFURL *)alertSoundURL;
+ (BOOL)isRunningInInstallEnvironment;
- (id)init;
- (void)dealloc;
- (void)setDefaultShell:(id)arg1;
- (id)defaultShell;
- (BOOL)authorizeShell;
- (void)awakeFromNib;
- (void)setDockMenu:(id)arg1;
- (void)finishLaunching;
- (void)applicationDidFinishLaunching:(id)arg1;
- (void)migrateDefaults;
- (id)importDefaultSettingsOverwritingExisting:(BOOL)arg1;
- (void)newShell:(id)arg1;
- (void)newTab:(id)arg1;
- (void)newShell:(id)arg1 withProfile:(id)arg2;
- (id)newWindowControllerWithProfile:(id)arg1;
- (id)newWindowControllerWithProfile:(id)arg1 command:(id)arg2 runAsShell:(BOOL)arg3;
- (BOOL)applicationShouldHandleReopen:(id)arg1 hasVisibleWindows:(BOOL)arg2;
- (void)showPreferencesWindow:(id)arg1;
- (void)sneakilyOrderFrontFontPanel:(id)arg1;
- (void)toggleProfileInspector:(id)arg1;
- (void)toggleInspectorPanel:(id)arg1;
- (void)open:(id)arg1;
- (BOOL)application:(id)arg1 openTempFile:(id)arg2;
- (void)connectToServer:(id)arg1;
- (BOOL)application:(id)arg1 openFile:(id)arg2;
- (unsigned long long)applicationShouldTerminate:(id)arg1;
- (void)continueTermination:(id)arg1;
- (void)cancelTermination:(id)arg1;
- (void)didPresentErrorWithRecovery:(BOOL)arg1 contextInfo:(void *)arg2;
- (BOOL)openFile:(id)arg1;
- (void)newCommand:(id)arg1;
- (BOOL)openCommandFile:(id)arg1;
- (BOOL)openTermFile:(id)arg1;
- (id)importTermFile:(id)arg1;
- (BOOL)openSettingsFile:(id)arg1;
- (BOOL)importSettingsFiles:(id)arg1 overwritingExisting:(BOOL)arg2 profiles:(id *)arg3 workspaces:(id *)arg4 error:(id *)arg5;
- (void)applyProfileToAllWindowControllers:(id)arg1;
- (void)handleWindowKeyChange:(id)arg1;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)applicationDidResignActive:(id)arg1;
- (void)addWindowController:(id)arg1;
- (void)addWindowController:(id)arg1 withProfileID:(int)arg2;
- (id)currentWorkspace;
- (void)saveWorkspace:(id)arg1;
- (void)openWorkspace:(id)arg1;
- (void)openWorkspaceRepresentation:(id)arg1;
- (id)mainTerminalWindow;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)setSecureKeyboardEntryFromDefaults;
- (void)setSecureKeyboardEntry:(BOOL)arg1;
- (void)toggleSecureKeyboardEntry:(id)arg1;
- (void)showHelpAnchorWithTag:(id)arg1;
- (BOOL)validateMenuItem:(id)arg1;
- (void)updateShellMenu;
- (void)updateWindowMenu;
- (void)addWindowsItem:(id)arg1 title:(id)arg2 filename:(BOOL)arg3;
- (void)changeWindowsItem:(id)arg1 title:(id)arg2 filename:(BOOL)arg3;
- (void)updateWindowsItem:(id)arg1;
- (void)removeWindowsItem:(id)arg1;
- (void)profileMenuNeedsUpdate:(id)arg1;
- (void)profileMenuNeedsUpdate:(id)arg1 withAction:(SEL)arg2;
- (void)workspaceMenuNeedsUpdate:(id)arg1;
- (unsigned long long)registerProfileID:(id)arg1;
- (void)releaseProfileID:(unsigned long long)arg1;
- (id)keyEquivalentForProfileID:(unsigned long long)arg1;
- (unsigned long long)keyEquivalentModifierMaskForProfileID:(unsigned long long)arg1;
- (void)sendEvent:(id)arg1;
- (void)orderFrontStandardAboutPanel:(id)arg1;
- (void)handleReceivedLowSwapSpaceSetNotification;
- (void)handleReceivedLowSwapSpaceClearedNotification;
- (void)watchForLowSwapSpace;
- (void)initLowSwapSpaceWatcher;
- (void)terminateLowSpaceWatcher;
- (void)searchForItemsWithSearchString:(id)arg1 resultLimit:(long long)arg2 matchedItemHandler:(id)arg3;
- (id)localizedTitlesForItem:(id)arg1;
- (id)localizedCategoryForItem:(id)arg1;
- (void)performActionForItem:(id)arg1;
@property BOOL isInEmergencyMemoryConservationMode; // @synthesize isInEmergencyMemoryConservationMode;

@end

