/*
 *     Generated by class-dump 3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class TTLogicalScreen;

@interface TTAttributedString : NSObject
{
    CDStruct_bff1fa32 *_chars;
    CDStruct_bff1fa32 *_runs;
    unsigned long long _width;
    unsigned long long _insertionColumn;
    unsigned long long _insertionCharOffset;
    unsigned long long _insertionRunIndex;
    unsigned long long _insertionRunOffset;
    TTLogicalScreen *_screen;
    unsigned long long _size;
}

- (id)initWithLogicalScreen:(id)arg1;
- (void)dealloc;
- (id)description;
- (unsigned long long)width;
- (void)updateWidth;
- (unsigned long long)size;
- (void)setSize:(unsigned long long)arg1;
- (CDStruct_bff1fa32 *)chars;
- (CDStruct_bff1fa32 *)runs;
- (void)insertUTF8Characters:(const char *)arg1 length:(unsigned long long)arg2 width:(unsigned long long)arg3 withAttributes:(CDStruct_45ade667)arg4 atColumn:(unsigned long long)arg5;
- (void)overwriteUTF8Characters:(const char *)arg1 length:(unsigned long long)arg2 width:(unsigned long long)arg3 withAttributes:(CDStruct_45ade667)arg4 atColumn:(unsigned long long)arg5;
- (void)deleteCharactersInColumnRange:(struct _NSRange)arg1;
- (void)deleteAllCharacters;
- (void)appendToStorageManager:(id)arg1 withNewline:(BOOL)arg2;
- (void)advanceInsertionPointToColumn:(unsigned long long)arg1 fillingSpaceIfNecessary:(BOOL)arg2;
- (void)validate;
- (void)getUTF8Characters:(CDStruct_bff1fa32 *)arg1 runs:(CDStruct_bff1fa32 *)arg2;

@end

