/*
 *     Generated by class-dump 3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableSet, NSTimer;

@interface TTBlinker : NSObject
{
    NSTimer *_timer;
    NSMutableSet *_targets;
    BOOL _flag;
    BOOL _isHidden;
    BOOL _isSessionActive;
}

+ (id)sharedBlinker;
- (id)init;
- (void)dealloc;
- (void)addTarget:(id)arg1;
- (void)removeTarget:(id)arg1;
- (BOOL)containsTarget:(id)arg1;
- (void)dispatchBlink:(id)arg1;
- (void)applicationDidUnhide:(id)arg1;
- (void)applicationDidHide:(id)arg1;
- (void)sessionDidBecomeActive:(id)arg1;
- (void)sessionDidResignActive:(id)arg1;
- (void)updateTimer;

@end

