/*
 *     Generated by class-dump 3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "TTProfile.h"

@interface TTBuiltinProfile : TTProfile
{
}

+ (id)sharedBuiltinProfile;
+ (id)defaultKeyMappings;
- (id)init;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (id)name;
- (void)setName:(id)arg1;
- (void)setParentProfile:(id)arg1;
- (void)setScopeValue:(id)arg1 forKey:(id)arg2;

@end

