/*
 *     Generated by class-dump 3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSClipView.h"

@interface TTClipView : NSClipView
{
    double _documentHeight;
    struct CGPoint _lastScrollPoint;
}

- (void)setDocumentView:(id)arg1;
- (void)viewFrameChanged:(id)arg1;
- (void)scrollToPoint:(struct CGPoint)arg1;

@end

