/*
 *     Generated by class-dump 3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@interface TTEncodingBindingEntry : NSObject
{
    unsigned long long _encoding;
}

+ (id)bindingEntryWithEncoding:(unsigned long long)arg1;
- (id)initWithEncoding:(unsigned long long)arg1;
- (void)dealloc;
- (id)localizedName;
- (unsigned long long)encoding;
- (BOOL)isEnabled;
- (void)setEnabled:(BOOL)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;

@end

