/*
 *     Generated by class-dump 3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "TTEncodingConverter.h"

@interface TTEncodingConverter (PrivateMethods)
- (id)alignData:(id)arg1 usingEncoding:(unsigned long long)arg2;
- (id)_utf8ValidateData:(id)arg1 pushBack:(BOOL)arg2;
- (id)_iso2022jpValidateData:(id)arg1 pushBack:(BOOL)arg2;
- (id)_validateData:(id)arg1 pushBack:(BOOL)arg2 encoding:(unsigned long long)arg3;
@end

