/*
 *     Generated by class-dump 3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

#import "TTOutputDecoder-Protocol.h"

@class NSMutableData, TTProfile;

@interface TTEncodingConverter : NSObject <TTOutputDecoder>
{
    TTProfile *_profile;
    NSMutableData *_inputBuffer;
    int _iso2022jpCSState;
    unsigned long long _stringEncoding;
}

+ (id)localeCompliantStringFromEncoding:(unsigned int)arg1;
- (id)initWithController:(id)arg1;
- (id)initWithProfile:(id)arg1;
- (void)dealloc;
- (id)profile;
- (void)setProfile:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (id)decodeData:(id)arg1;
- (void)softReset;
- (void)hardReset;

@end

