/*
 *     Generated by class-dump 3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class NSArray;

@interface TTEncodingController : NSObject
{
    NSArray *_availableEncodings;
    NSArray *_enabledEncodings;
    unsigned long long _transientEncoding;
}

+ (void)initialize;
+ (id)defaultEncodings;
+ (id)sharedEncodingController;
- (id)init;
- (void)dealloc;
- (void)setTransientEncoding:(unsigned long long)arg1;
- (id)availableEncodings;
- (id)enabledEncodings;
- (void)enableAll:(id)arg1;
- (void)disableAll:(id)arg1;
- (void)revertToDefaults:(id)arg1;
- (void)enabledEncodingsDidChange;
- (id)enabledEncodingsArray;

@end

