/*
 *     Generated by class-dump 3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@protocol TTEventEncoder
- (id)initWithController:(id)arg1;
- (id)encodeEvent:(id)arg1;
@end

