/*
 *     Generated by class-dump 3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSPanel.h"

@class NSButton, NSComboBox, NSTextField;

@interface TTFindPanel : NSPanel
{
    NSComboBox *_findPatternField;
    NSButton *_findNextButton;
    NSButton *_findPreviousButton;
    NSButton *_ignoreCaseCheckbox;
    NSButton *_wrapAroundCheckbox;
    NSTextField *_notFoundLabel;
    BOOL _isFindPatternDirty;
}

+ (id)sharedFindPanel;
- (id)initWithContentRect:(struct CGRect)arg1 styleMask:(unsigned long long)arg2 backing:(unsigned long long)arg3 defer:(BOOL)arg4;
- (void)dealloc;
- (id)findPattern;
- (unsigned long long)stringCompareOptions;
- (void)performTerminalFindPanelAction:(id)arg1;
- (void)findNext:(id)arg1;
- (void)findNextAndOrderOutOnMatch:(id)arg1;
- (void)findPrevious:(id)arg1;
- (void)becomeKeyWindow;
- (BOOL)validateMenuItem:(id)arg1;
- (void)controlTextDidChange:(id)arg1;
- (void)comboBoxSelectionDidChange:(id)arg1;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)initContentView;
- (void)pushChangesToPasteboard;
- (void)pullChangesFromPasteboard;
- (void)updateRecentPatterns;
- (id)target;
- (BOOL)conformsToFindingProtocol:(id)arg1;
- (void)performFindWithOptions:(unsigned long long)arg1 orderOutOnMatch:(BOOL)arg2;

@end

