/*
 *     Generated by class-dump 3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSWindowController.h"

@class NSArray, NSBox, NSButton, NSComboBoxCell, NSString, NSViewController;

@interface TTGenericSavePanel : NSWindowController
{
    NSString *_name;
    NSString *_objectName;
    BOOL _isObjectNameCountable;
    NSString *_title;
    NSArray *_representedObjects;
    NSViewController *_accessoryController;
    BOOL _isDisplayingSheet;
    id _modalForWindow;
    id _modalDelegate;
    SEL _didEndSelector;
    NSComboBoxCell *_nameField;
    NSButton *_saveButton;
    NSButton *_cancelButton;
    NSBox *_accessoryBox;
    NSBox *_lineBox;
}

+ (id)savePanel;
- (id)init;
- (void)dealloc;
- (void)setName:(id)arg1;
- (id)name;
- (void)setObjectName:(id)arg1;
- (id)objectName;
- (void)setObjectNameCountable:(BOOL)arg1;
- (BOOL)isObjectNameCountable;
- (id)title;
- (void)setTitle:(id)arg1;
- (void)setRepresentedObjects:(id)arg1;
- (id)representedObjects;
- (void)setAccessoryController:(id)arg1;
- (id)accessoryController;
- (void)beginSheetModalForWindow:(id)arg1 modalDelegate:(id)arg2 didEndSelector:(SEL)arg3;
- (long long)runModal;
- (void)sheetDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (void)sheetDidEndWithReturnCode:(long long)arg1;
- (id)windowNibName;
- (void)save:(id)arg1;
- (void)didPresentErrorWithRecovery:(BOOL)arg1 contextInfo:(void *)arg2;
- (void)alertDidEnd:(id)arg1 returnCode:(int)arg2 contextInfo:(void *)arg3;
- (void)cancel:(id)arg1;
- (void)endWithReturnCode:(long long)arg1;
- (void)preparePanel;
- (void)handleComboBoxChange:(id)arg1;
- (void)controlTextDidChange:(id)arg1;

@end

