/*
 *     Generated by class-dump 3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSWindowController.h"

@class NSArray, NSButton, NSString, NSTextField;

@interface TTGenericPickerPanel : NSWindowController
{
    id _representedObject;
    id _defaultRepresentedObject;
    NSArray *_representedObjects;
    NSString *_title;
    NSString *_prompt;
    NSString *_message;
    id _modalDelegate;
    SEL _didEndSelector;
    NSButton *_defaultButton;
    NSTextField *_messageField;
}

+ (id)pickerPanel;
- (id)init;
- (void)dealloc;
- (id)representedObjects;
- (void)setRepresentedObjects:(id)arg1;
- (id)title;
- (void)setTitle:(id)arg1;
- (id)prompt;
- (void)setPrompt:(id)arg1;
- (id)message;
- (void)setMessage:(id)arg1;
- (id)representedObject;
- (void)setRepresentedObject:(id)arg1;
- (id)defaultRepresentedObject;
- (void)setDefaultRepresentedObject:(id)arg1;
- (void)beginSheetModalForWindow:(id)arg1 modalDelegate:(id)arg2 didEndSelector:(SEL)arg3;
- (long long)runModal;
- (void)open:(id)arg1;
- (void)cancel:(id)arg1;
- (id)windowNibName;
- (void)endWithReturnCode:(long long)arg1;
- (void)sheetDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (void)preparePanel;
- (void)prepareRepresentedObject;

@end

