/*
 *     Generated by class-dump 3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@interface TTKeyMapTextEscaper : NSObject
{
    unsigned short *_buf;
    int _buflen;
}

- (void)dealloc;
- (id)escapeString:(id)arg1;
- (id)unescapeString:(id)arg1;

@end

