/*
 *     Generated by class-dump 3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "TTLogicalScreen.h"

@interface TTLogicalScreen (UnicharAccessInternal)
- (void)initUnicharAccess;
- (void)deallocUnicharAccess;
- (unsigned long long)unicharOffsetCacheGenerationNumber;
- (void)expandUnicharOffsetCacheToLine:(unsigned long long)arg1;
- (unsigned long long)unicharOffsetForLine:(unsigned long long)arg1;
- (unsigned long long)reverseUnicharOffsetForDisplayPosition:(CDStruct_4bcfbbae)arg1;
- (CDStruct_4bcfbbae)displayPositionForReverseUnicharOffset:(unsigned long long)arg1;
@end

