/*
 *     Generated by class-dump 3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSString.h"

@class TTLogicalScreen;

@interface TTLogicalScreenString : NSString
{
    TTLogicalScreen *_screen;
    CDStruct_bff1fa32 *_UTF8Buffer;
    CDStruct_bff1fa32 *_UTF16Buffer;
    CDStruct_bff1fa32 *_runBuffer;
    struct _NSRange _backingStoreRange;
    unsigned long long _generation;
}

+ (id)stringWithLogicalScreen:(id)arg1;
- (id)initWithLogicalScreen:(id)arg1;
- (void)dealloc;
- (unsigned long long)length;
- (unsigned long long)activeLength;
- (unsigned long long)offsetToActiveArea;
- (unsigned short)characterAtIndex:(unsigned long long)arg1;
- (struct _NSRange)rangeOfString:(id)arg1 options:(unsigned long long)arg2 range:(struct _NSRange)arg3 locale:(id)arg4;
- (void)getCharacters:(unsigned short *)arg1 range:(struct _NSRange)arg2;

@end

