/*
 *     Generated by class-dump 3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "TTLogicalScreen.h"

@interface TTLogicalScreen (VT100Additions)
- (void)eraseUTF8Characters:(unsigned long long)arg1 withAttributes:(CDStruct_45ade667)arg2 atPosition:(CDStruct_4bcfbbae)arg3;
@end

