/*
 *     Generated by class-dump 3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@interface TTMultiLineBuffer : NSObject
{
    CDStruct_bff1fa32 *_chars;
    CDStruct_bff1fa32 *_runs;
    CDStruct_bff1fa32 *_lineOffsets;
    BOOL _isTextWrapped;
    unsigned long long _columnCount;
    unsigned long long utf16CharacterCount;
}

- (id)initWithColumnCount:(unsigned long long)arg1;
- (void)reinitializeWithColumnCount:(unsigned long long)arg1;
- (void)dealloc;
- (id)description;
- (BOOL)isTextWrapped;
- (void)setTextWrapped:(BOOL)arg1;
- (unsigned long long)columnCount;
- (unsigned long long)length;
- (CDStruct_bff1fa32 *)chars;
- (CDStruct_bff1fa32 *)runs;
- (CDStruct_bff1fa32 *)lineOffsets;
- (void)setLineOffsets:(CDStruct_bff1fa32 *)arg1;
- (CDStruct_0ef95e2a *)firstRunAtLineOffset:(unsigned long long)arg1 returnIndex:(unsigned long long *)arg2;
- (void)getLine:(unsigned long long)arg1 UTF8Characters:(CDStruct_bff1fa32 *)arg2 runs:(CDStruct_bff1fa32 *)arg3;
- (void)appendUTF8Characters:(const char *)arg1 length:(unsigned long long)arg2 withAttributes:(CDStruct_45ade667)arg3 doesBeginLine:(BOOL)arg4;
- (void)truncateToCharacterLength:(unsigned long long)arg1;
- (void)truncateToLineLength:(unsigned long long)arg1;
- (void)deleteLinesFromBeginning:(unsigned long long)arg1;
- (unsigned long long)wrapToColumnCount:(unsigned long long)arg1 startingAtColumn:(unsigned long long)arg2 withLogicalScreen:(id)arg3;
- (unsigned long long)wrapLineOffsets:(CDStruct_bff1fa32 *)arg1 toColumnCount:(unsigned long long)arg2 startingAtColumn:(unsigned long long)arg3 withLogicalScreen:(id)arg4;
@property unsigned long long utf16CharacterCount; // @synthesize utf16CharacterCount;

@end

