/*
 *     Generated by class-dump 3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "TTAccessibleView.h"

@class NSButton, NSScroller, TTLogicalScreen, TTSplitView, TTTabController, TTView;

@interface TTPane : TTAccessibleView
{
    TTView *view;
    NSScroller *scroller;
    TTSplitView *splitView;
    TTTabController *controller;
    TTLogicalScreen *logicalScreen;
    BOOL paneCanBeClosed;
    NSButton *_splitButton;
    NSButton *_closeButton;
}

- (void)dealloc;
@property(readonly) BOOL isActive;
- (BOOL)isResizePane;
@property(readonly) BOOL paneCanBeClosed; // @synthesize paneCanBeClosed;
@property(readonly) BOOL paneCanBeSplit;
- (void)updateGeometry;
- (id)initWithFrame:(struct CGRect)arg1 withSplitView:(id)arg2 withController:(id)arg3 withProfile:(id)arg4 logicalScreen:(id)arg5;
- (struct CGSize)contentSize;
- (struct CGSize)contentSizeForLogicalContentSize:(struct CGSize)arg1;
- (void)sizeToFit:(struct CGRect)arg1;
- (void)setProfile:(id)arg1;
@property TTTabController *controller;
- (void)drawRect:(struct CGRect)arg1;
- (void)splitPressed:(id)arg1;
- (void)closePressed:(id)arg1;
- (void)scrollWheel:(id)arg1;
- (void)scrollToTop;
- (void)scrollToBottom;
- (void)lineUp;
- (void)lineDown;
- (void)pageUp;
- (void)pageDown;
- (void)updateFromScroller:(id)arg1;
- (id)accessibilityAttributeNames;
- (id)ttaxRoleAttribute;
- (BOOL)ttaxIsRoleAttributeMutable;
- (id)ttaxRoleDescriptionAttribute;
- (BOOL)ttaxIsRoleDescriptionAttributeMutable;
- (id)ttaxHorizontalScrollBarAttribute;
- (BOOL)ttaxIsHorizontalScrollBarAttributeMutable;
- (id)ttaxVerticalScrollBarAttribute;
- (BOOL)ttaxIsVerticalScrollBarAttributeMutable;
- (id)ttaxContentsAttribute;
- (BOOL)ttaxIsContentsAttributeMutable;
- (id)ttaxFocusedAttribute;
- (BOOL)ttaxIsFocusedAttributeMutable;
- (void)ttaxSetFocusedAttribute:(id)arg1;
@property TTSplitView *splitView; // @synthesize splitView;
@property TTLogicalScreen *logicalScreen; // @synthesize logicalScreen;
@property NSScroller *scroller; // @synthesize scroller;
@property TTView *view; // @synthesize view;

@end

