/*
 *     Generated by class-dump 3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "TTProfile.h"

@interface TTProfile (Scripting)
- (id)objectSpecifier;
- (id)scriptUniqueID;
- (id)scriptNumberOfRows;
- (void)setScriptNumberOfRows:(id)arg1;
- (id)scriptNumberOfColumns;
- (void)setScriptNumberOfColumns:(id)arg1;
- (id)scriptCursorColor;
- (void)setScriptCursorColor:(id)arg1;
- (id)scriptBackgroundColor;
- (void)setScriptBackgroundColor:(id)arg1;
- (id)scriptNormalTextColor;
- (void)setScriptNormalTextColor:(id)arg1;
- (id)scriptBoldTextColor;
- (void)setScriptBoldTextColor:(id)arg1;
- (id)scriptFontName;
- (void)setScriptFontName:(id)arg1;
- (int)scriptFontSize;
- (void)setScriptFontSize:(int)arg1;
- (BOOL)scriptFontAntialiasing;
- (void)setScriptFontAntialiasing:(BOOL)arg1;
- (id)scriptCleanCommands;
- (void)setScriptCleanCommands:(id)arg1;
- (BOOL)scriptTitleDisplaysDeviceName;
- (void)setScriptTitleDisplaysDeviceName:(BOOL)arg1;
- (BOOL)scriptTitleDisplaysShellPath;
- (void)setScriptTitleDisplaysShellPath:(BOOL)arg1;
- (BOOL)scriptTitleDisplaysWindowSize;
- (void)setScriptTitleDisplaysWindowSize:(BOOL)arg1;
- (BOOL)scriptTitleDisplaysSettingsName;
- (void)setScriptTitleDisplaysSettingsName:(BOOL)arg1;
- (BOOL)scriptTitleDisplaysCustomTitle;
- (void)setScriptTitleDisplaysCustomTitle:(BOOL)arg1;
- (id)scriptCustomTitle;
- (void)setScriptCustomTitle:(id)arg1;
@end

