/*
 *     Generated by class-dump 3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "TTProfileManager.h"

@interface TTProfileManager (UndoCompatibleKeyValueCoding)
- (void)undoCompatibleSetValue:(id)arg1 forKeyPath:(id)arg2;
- (void)undoCompatibleInsertObjects:(id)arg1 intoKeyPath:(id)arg2;
- (void)undoCompatibleRemoveObjects:(id)arg1 fromKeyPath:(id)arg2;
- (void)undoCompatibleReplaceObjects:(id)arg1 withObjects:(id)arg2 atKeyPath:(id)arg3;
@end

