/*
 *     Generated by class-dump 3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray, TTProfile;

@interface TTProfileManager : NSObject
{
    NSMutableArray *_profiles;
    TTProfile *_defaultProfile;
    TTProfile *_startupProfile;
    BOOL _isLoadingFromDefaults;
}

+ (id)sharedProfileManager;
- (id)init;
- (void)dealloc;
- (void)synchronize;
- (id)profiles;
- (void)setProfiles:(id)arg1;
- (unsigned long long)countOfProfiles;
- (void)insertObject:(id)arg1 inProfilesAtIndex:(unsigned long long)arg2;
- (void)removeObjectFromProfilesAtIndex:(unsigned long long)arg1;
- (void)replaceObjectInProfilesAtIndex:(unsigned long long)arg1 withObject:(id)arg2;
- (id)profileWithName:(id)arg1;
- (void)setProfile:(id)arg1 forName:(id)arg2;
- (id)uniqueProfileNameWithBase:(id)arg1;
- (id)defaultProfile;
- (void)setDefaultProfile:(id)arg1;
- (id)startupProfile;
- (void)setStartupProfile:(id)arg1;
- (id)profileSavePanel;

@end

