/*
 *     Generated by class-dump 3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableIndexSet, NSThread, TTLogicalScreen;

@interface TTScrollbackTextStorage : NSObject
{
    TTLogicalScreen *_screen;
    struct storage_list *_freeListHead;
    struct storage_list *_freeListTail;
    unsigned long long _freeListCount;
    CDStruct_bff1fa32 *_storageList;
    unsigned long long _cursorIndex;
    unsigned long long _cursorOffsetIndex;
    unsigned long long _characterCount;
    unsigned long long _lineCount;
    unsigned long long _columnCount;
    NSMutableIndexSet *_doubleHighTopLines;
    NSMutableIndexSet *_doubleHighBottomLines;
    NSMutableIndexSet *_doubleWideLines;
    NSThread *_rewrappingThread;
}

- (id)initWithLogicalScreen:(id)arg1;
- (void)dealloc;
- (id)description;
- (unsigned long long)lineCount;
- (unsigned long long)columnCount;
- (void)setColumnCount:(unsigned long long)arg1;
- (void)rewrappingThread:(id)arg1;
- (void)applyChangesFromRewrappingThread:(id)arg1;
- (void)wrapLinesFromEnd:(unsigned long long)arg1 toColumnCount:(unsigned long long)arg2;
- (BOOL)initializeFreeList;
- (BOOL)growFreeList:(unsigned long long)arg1;
- (BOOL)growFreeList;
- (void)shrinkFreeList;
- (void)deleteFreeList;
- (BOOL)createBuffer;
- (void)releaseStorageListTail;
- (void)releaseStorageListHead;
- (BOOL)initializeStorageList;
- (void)deleteStorageList;
- (void)getLine:(unsigned long long)arg1 UTF8Characters:(CDStruct_bff1fa32 *)arg2 runs:(CDStruct_bff1fa32 *)arg3;
- (id)bufferAtIndex:(unsigned long long)arg1;
- (unsigned long long)bufferCount;
- (void)appendUTF8Characters:(const char *)arg1 length:(unsigned long long)arg2 withAttributes:(CDStruct_45ade667)arg3 doesBeginLine:(BOOL)arg4;
- (void)clearStorageList;
- (void)truncateToCharacterLength:(unsigned long long)arg1;
- (void)truncateToLineLength:(unsigned long long)arg1;
- (void)truncateToExactLineLength:(unsigned long long)arg1;
- (void)truncateFromBeginningToExactLineLength:(unsigned long long)arg1;
- (unsigned long long)sizeForLine:(unsigned long long)arg1;
- (void)setSize:(unsigned long long)arg1 forLine:(unsigned long long)arg2;
- (void)rewindCursor;
- (void)truncateLineSizes;
- (void)truncateLineSizesFromBeginningFrom:(unsigned long long)arg1 to:(unsigned long long)arg2;

@end

