/*
 *     Generated by class-dump 3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class NSConditionLock, NSMutableArray, NSThread;

@interface TTShellReaper : NSObject
{
    NSMutableArray *_shellArray;
    NSThread *_thread;
    NSConditionLock *_conditionLock;
}

+ (id)sharedReaper;
- (id)init;
- (void)dealloc;
- (void)reapShell:(id)arg1;
- (void)reapShellsInArray:(id)arg1;
- (void)wait;
- (void)grimReaper;

@end

