/*
 *     Generated by class-dump 3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSSplitView.h"

@class TTTabController;

@interface TTSplitView : NSSplitView
{
    TTTabController *tabController;
}

- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;
- (double)dividerThickness;
- (id)dividerColor;
- (void)setProfile:(id)arg1;
- (void)setSelectedProfile:(id)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (void)adjustSubviews;
- (struct CGSize)contentSizeForLogicalContentSize:(struct CGSize)arg1;
@property TTTabController *tabController; // @synthesize tabController;

@end

