/*
 *     Generated by class-dump 3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSTabViewDelegate-Protocol.h"

@protocol TTTabViewDelegate <NSTabViewDelegate>
- (void)tabView:(id)arg1 didSelectTabViewItem:(id)arg2;
- (BOOL)shouldCloseTabViewItem:(id)arg1;
- (void)tabView:(id)arg1 didCloseTabViewItem:(id)arg2;
- (void)tabView:(id)arg1 didDragTabViewItemOutOfWindow:(id)arg2 toPoint:(struct CGPoint)arg3;
- (void)tabView:(id)arg1 draggingTabViewItemOutOfWindow:(id)arg2 toPoint:(struct CGPoint)arg3;
- (void)tabView:(id)arg1 didDropTabViewItemOutOfWindow:(struct CGPoint)arg2;
@end

