/*
 *     Generated by class-dump 3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSTableView.h"

@class NSString;

@interface TTTableView : NSTableView
{
    NSString *_emptyMessage;
}

- (void)dealloc;
- (id)emptyMessageAttributes;
- (id)emptyMessage;
- (void)setEmptyMessage:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;

@end

