/*
 *     Generated by class-dump 3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSTabViewItem.h"

#import "NSAnimationDelegate-Protocol.h"

@class NSCell, NSImage, TTTabAlertAnimation, TTTabController;

@interface TTTabViewItem : NSTabViewItem <NSAnimationDelegate>
{
    TTTabController *tabController;
    NSImage *_alertImage;
    NSCell *_labelCell;
    TTTabAlertAnimation *_alertAnimation;
    struct CGRect _rect;
    struct CGRect _closeRect;
    struct CGRect _alertRect;
    struct CGRect _labelRect;
    BOOL _alertEnabled;
    BOOL _isBeingDraggedFromOutside;
    BOOL _willDisableAlert;
    BOOL _showCloseImage;
    BOOL _isClosing;
    BOOL _willClose;
    BOOL _isOffScreen;
    float _closingProgress;
    float _closeOpacity;
    float _isTabHighlighted;
    BOOL _isBeingDragged;
    BOOL _isBeingReordered;
    BOOL _isSpringingBack;
    float _alertFadingProgress;
    float _reorderProgress;
    float _springBackProgress;
    int _reorderState;
    long long _toolTipTag;
    BOOL _isSlidingInTabBar;
}

- (id)initWithIdentifier:(id)arg1;
- (void)dealloc;
- (void)animationDidEnd:(id)arg1;
- (void)drawTabViewItem:(struct CGRect)arg1;
- (void)removeToolTip;
- (void)_drawImage:(id)arg1 inRect:(struct CGRect)arg2 withOpacity:(float)arg3;
- (void)_drawLabel:(struct CGRect)arg1;
- (struct CGRect)_determineRectForImage:(id)arg1;
- (void)setIsBeingDragged:(BOOL)arg1;
- (BOOL)isBeingDragged;
- (void)setIsSpringingBack:(BOOL)arg1;
- (float)closingProgress;
- (BOOL)isSpringingBack;
- (void)setState:(unsigned long long)arg1;
- (void)setIsBeingReordered:(BOOL)arg1;
- (void)setIsOffScreen:(BOOL)arg1;
- (BOOL)isOffScreen;
- (BOOL)isTabHighlighted;
- (void)setReorderState:(int)arg1;
- (int)reorderState;
- (void)setSpringBackProgress:(float)arg1;
- (float)springBackProgress;
- (void)setReorderProgress:(float)arg1;
- (float)reorderProgress;
- (void)setWillClose:(BOOL)arg1;
- (BOOL)willClose;
- (void)setAlertFadingProgress:(float)arg1;
- (float)alertFadingProgress;
- (void)setAlertImage:(id)arg1;
- (void)setShowCloseImage:(BOOL)arg1;
- (void)setIsBeingDraggedFromOutside:(BOOL)arg1;
- (BOOL)isBeingDraggedFromOutside;
- (struct CGRect)rect;
- (struct CGRect)closeRect;
- (struct CGRect)labelRect;
- (void)setIsSlidingInTabBar:(BOOL)arg1;
- (BOOL)isSlidingInTabBar;
- (void)disableAlert;
- (void)enableAlert;
- (void)lightenTab;
- (void)darkenTab;
- (void)lightenCloseImage;
- (void)darkenCloseImage;
- (void)darkenMoreCloseImage;
- (BOOL)accessibilityIsIgnored;
@property(retain) TTTabController *tabController; // @synthesize tabController;

@end

