/*
 *     Generated by class-dump 3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSAnimation.h"

@class TTTabViewItem;

@interface TTTabAnimation : NSAnimation
{
    TTTabViewItem *_tab;
}

- (void)dealloc;
- (id)tab;
- (void)setTab:(id)arg1;

@end

