/*
 *     Generated by class-dump 3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@interface TTTermFileConverter : NSObject
{
}

+ (id)convertTermFile:(id)arg1;
+ (id)convertTermFile:(id)arg1 forceWorkspace:(BOOL)arg2;
+ (id)profileWithDefaults:(id)arg1 name:(id)arg2;
+ (id)profileWithDefaults:(id)arg1 name:(id)arg2 origin:(struct CGPoint *)arg3 isUpperLeftOrigin:(char *)arg4;
+ (id)workspaceRepresentationWithDefaultsArray:(id)arg1 name:(id)arg2;
+ (BOOL)convertKey:(id)arg1 value:(id)arg2 profile:(id)arg3;
+ (id)convertBooleanValue:(id)arg1;
+ (id)convertIntegerValue:(id)arg1;
+ (id)convertFloatValue:(id)arg1;
+ (void)convertBackgroundImagePath:(id)arg1 profile:(id)arg2;
+ (void)convertTextColors:(id)arg1 profile:(id)arg2;
+ (void)convertNSFixedPitchFont:(id)arg1 profile:(id)arg2;
+ (void)convertCursorShape:(id)arg1 profile:(id)arg2;
+ (void)convertTitleBits:(id)arg1 profile:(id)arg2;
+ (void)convertMeta:(id)arg1 profile:(id)arg2;
+ (void)convertExecutionString:(id)arg1 profile:(id)arg2;
+ (void)convertShell:(id)arg1 profile:(id)arg2;
+ (void)convertSaveLines:(id)arg1 profile:(id)arg2;
+ (id)mappingDictionary;
+ (id)typeMappingDictionary;

@end

