/*
 *     Generated by class-dump 3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "TTProfile.h"

@class TTTabController;

@interface TTTemporaryProfile : TTProfile
{
    TTTabController *_controller;
}

- (void)dealloc;
- (id)objectSpecifier;
- (void)setTabController:(id)arg1;

@end

