/*
 *     Generated by class-dump 3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"

@class NSString;

@interface TTUUID : NSObject <NSCopying, NSCoding>
{
    struct __CFUUID *_uuid;
    NSString *_uuidString;
}

+ (id)UUID;
- (id)init;
- (id)initWithUUIDRef:(struct __CFUUID *)arg1;
- (void)dealloc;
- (BOOL)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)string;
- (id)stringValue;
- (struct __CFUUID *)UUIDRef;
- (long long)compare:(id)arg1;

@end

