/*
 *     Generated by class-dump 3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "TTView.h"

@interface TTView (TTAccessibility)
+ (struct CGRect)convertScreenToAccessibility:(struct CGRect)arg1;
- (id)accessibilityAttributeNames;
- (id)accessibilityParameterizedAttributeNames;
- (id)ttaxRoleAttribute;
- (BOOL)ttaxIsRoleAttributeMutable;
- (id)ttaxDescriptionAttribute;
- (BOOL)ttaxIsDescriptionAttributeMutable;
- (id)ttaxSizeAttribute;
- (BOOL)ttaxIsSizeAttributeMutable;
- (id)ttaxPositionAttribute;
- (BOOL)ttaxIsPositionAttributeMutable;
- (id)ttaxValueAttribute;
- (BOOL)ttaxIsValueAttributeMutable;
- (id)ttaxNumberOfCharactersAttribute;
- (BOOL)ttaxIsNumberOfCharactersAttributeMutable;
- (id)ttaxSelectedTextAttribute;
- (BOOL)ttaxIsSelectedTextAttributeMutable;
- (id)ttaxSelectedTextRangeAttribute;
- (void)ttaxSetSelectedTextRangeAttribute:(id)arg1;
- (BOOL)ttaxIsSelectedTextRangeAttributeMutable;
- (id)ttaxSelectedTextRangesAttribute;
- (void)ttaxSetSelectedTextRangesAttribute:(id)arg1;
- (BOOL)ttaxIsSelectedTextRangesAttributeMutable;
- (id)ttaxInsertionPointLineNumberAttribute;
- (BOOL)ttaxIsInsertionPointLineNumberAttributeMutable;
- (id)ttaxVisibleCharacterRangeAttribute;
- (BOOL)ttaxIsVisibleCharacterRangeAttributeMutable;
- (id)ttaxLineForIndexAttributeForParameter:(id)arg1;
- (id)ttaxRangeForLineAttributeForParameter:(id)arg1;
- (id)ttaxStringForRangeAttributeForParameter:(id)arg1;
- (id)ttaxRangeForPositionAttributeForParameter:(id)arg1;
- (id)ttaxRangeForIndexAttributeForParameter:(id)arg1;
- (id)ttaxBoundsForRangeAttributeForParameter:(id)arg1;
- (void)ttaxEmulatorDidDecodeData:(id)arg1;
- (void)notifyAccessiblityAboutCursorLocation;
@end

