/*
 *     Generated by class-dump 3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "TTView.h"

@interface TTView (SelectionInternal)
+ (double)dragAndDropTextDelay;
- (void)initSelection;
- (void)deallocSelection;
- (struct CGPoint)pointByRoundingToCellBoundary:(struct CGPoint)arg1;
- (void)extendSelectionToMatchingCharacter;
- (unsigned short)matchingCharacterForCharacter:(unsigned short)arg1 matchType:(unsigned long long *)arg2;
- (void)moveCursorToPosition:(CDStruct_4bcfbbae)arg1 event:(id)arg2;
@end

