/*
 *     Generated by class-dump 3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "TTView.h"

@interface TTView (Selection)
- (void)selectTextBetweenDisplayPositions:(CDStruct_4bcfbbae)arg1 positionTwo:(CDStruct_4bcfbbae)arg2 rememberPositions:(BOOL)arg3;
- (void)appendSelectionToDisplayPosition:(CDStruct_4bcfbbae)arg1 rememberPositions:(BOOL)arg2;
- (void)findWordAtPosition:(CDStruct_4bcfbbae)arg1 startPosition:(CDStruct_4bcfbbae *)arg2 endPosition:(CDStruct_4bcfbbae *)arg3;
- (void)findLineAtPosition:(CDStruct_4bcfbbae)arg1 startPosition:(CDStruct_4bcfbbae *)arg2 endPosition:(CDStruct_4bcfbbae *)arg3;
- (void)findPathAtPosition:(CDStruct_4bcfbbae)arg1 startPosition:(CDStruct_4bcfbbae *)arg2 endPosition:(CDStruct_4bcfbbae *)arg3;
- (BOOL)selectionContainsDisplayPosition:(CDStruct_4bcfbbae)arg1;
- (void)clipSelectionRanges;
- (void)clearTextSelection;
- (void)setSelectedRange:(struct _NSRange)arg1;
- (void)setSelectedRanges:(id)arg1;
- (BOOL)hasSelection;
- (BOOL)hasActiveSelection;
- (void)selectionFlagsChanged:(id)arg1;
- (void)selectionMouseDown:(id)arg1;
- (void)selectionMouseUp:(id)arg1;
- (void)selectionMouseDragged:(id)arg1;
- (void)selectionOtherMouseDown:(id)arg1;
- (void)dragSelectionWithEvent:(id)arg1;
- (void)draggedImage:(id)arg1 endedAt:(struct CGPoint)arg2 operation:(unsigned long long)arg3;
@end

