/*
 *     Generated by class-dump 3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "TTView.h"

@interface TTView (Thumbnail)
- (double)thumbnailScaleFactorForSize:(struct CGSize)arg1;
- (struct CGSize)thumbnailSizeForSize:(struct CGSize)arg1;
- (id)thumbnailImageWithProfile:(id)arg1 size:(struct CGSize)arg2;
- (id)focusedThumbnailImageWithProfile:(id)arg1 size:(struct CGSize)arg2;
@end

