/*
 *     Generated by class-dump 3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

#import "TTEventEncoder-Protocol.h"
#import "TTOutputDecoder-Protocol.h"

@class NSMutableIndexSet, NSMutableString, TTLogicalScreen, TTProfile, TTShell, TTTabController;

@interface TTVT100Emulator : NSObject <TTEventEncoder, TTOutputDecoder>
{
    unsigned long long _state;
    TTLogicalScreen *_logicalScreen;
    TTShell *_shell;
    TTProfile *_profile;
    TTTabController *_controller;
    unsigned long long *_stateTable;
    unsigned long long *_defaultBaseStateTable;
    BOOL _screenSavedWrapState;
    unsigned int _numParams;
    int _params[32];
    NSMutableString *_operatingSystemCommand;
    struct _NSRange _scrollRange;
    BOOL _isScrollRangeActive;
    BOOL _isCursorInMargin;
    BOOL _isCursorSaved;
    struct {
        unsigned int cursorRow;
        unsigned int cursorColumn;
        unsigned int alternateCursorRow;
        unsigned int alternateCursorColumn;
        CDStruct_45ade667 attributes;
        char scrollRegionOrigin;
        unsigned long long rowCount;
        CDStruct_183601bc *translationTable[5][128];
    } _savedCursorState;
    struct {
        unsigned int linefeedNewline:1;
        unsigned int scrollRegionOrigin:1;
        unsigned int autoWrap:1;
        unsigned int reverseLineWrap:1;
        unsigned int keyboardAction:1;
        unsigned int autoRepeat:1;
        unsigned int applicationKeypad:1;
        unsigned int applicationCursor:1;
        unsigned int localEcho:1;
        unsigned int insertMode:1;
        unsigned int allowDECCOLM:1;
    } _modeFlags;
    CDStruct_45ade667 _currentAttributes;
    struct {
        unsigned char original;
        char *translated;
        unsigned int length;
        unsigned int custom:1;
    } _baseTranslationTable[128];
    char *_baseTranslationString;
    CDStruct_183601bc *_translationTable[5][128];
    unsigned int _currentCharSet;
    unsigned int _savedCharSet;
    unsigned int _selectedCharSet;
    unsigned int _shiftCharSet;
    BOOL _percentCharSet;
    BOOL _defaultTabStops;
    NSMutableIndexSet *_tabStops;
    BOOL _lastPrintedCharacter;
}

- (id)initWithShell:(id)arg1 logicalScreen:(id)arg2 profile:(id)arg3;
- (id)initWithController:(id)arg1;
- (void)dealloc;
- (id)profile;
- (void)setProfile:(id)arg1;
- (void)setObserversForLogicalScreen:(BOOL)arg1;
- (void)vt52EmulationMode:(BOOL)arg1;
- (void)softReset;
- (void)hardReset;
- (id)decodeData:(id)arg1;
- (id)encodeEvent:(id)arg1;
- (unsigned long long)cursorRow;
- (unsigned long long)unshiftedCursorRow;
- (void)advanceCursorRow;
- (void)setCursorRow:(unsigned long long)arg1;
- (unsigned int)rowCount;
- (unsigned long long)cursorColumn;
- (void)setCursorColumn:(unsigned long long)arg1;
- (void)setColumnCount:(unsigned long long)arg1;
- (void)setScrollRange:(struct _NSRange)arg1;
- (void)loadTranslationVector:(CDStruct_4c79594d *)arg1 intoSet:(unsigned int)arg2;
- (void)resetTabStops;
- (void)performOperatingSystemCommand;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;

@end

