/*
 *     Generated by class-dump 3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSWindowController.h"

#import "TTTabViewDelegate-Protocol.h"

@class NSMenu, NSMutableArray, TTTabController, TTTabView, TTTabViewItem;

@interface TTWindowController : NSWindowController <TTTabViewDelegate>
{
    NSMenu *_contextualMenu;
    NSMenu *_contextualMenuForSelection;
    NSMenu *_contextualMenuForTabItems;
    NSMenu *_contextualMenuForTabView;
    TTTabView *_tabView;
    NSMutableArray *_tabControllers;
    unsigned long long _windowProfileID;
    TTTabController *_selectedTabController;
    TTWindowController *_draggedController;
    TTWindowController *_receiverController;
    TTTabViewItem *_draggedTab;
    BOOL _isBeingDragged;
    id _delegate;
    struct CGRect _idealContentRect;
    long long _geometryUpdateDepth;
    BOOL _closeDialogExpected;
    struct CGPoint _cascadePoint;
    BOOL _hasAssignedFrame;
}

+ (void)initialize;
- (id)initWithWindow:(id)arg1;
- (void)dealloc;
- (id)windowNibName;
- (void)awakeFromNib;
- (void)setWindowProfileID:(unsigned long long)arg1;
- (unsigned long long)windowProfileID;
- (void)updateTitle;
- (void)updateAllTitles;
- (void)setDelegate:(id)arg1;
- (id)delegate;
- (void)updateAutosaveName;
- (struct CGSize)tabContentSize;
- (struct CGSize)contentSize;
- (void)updateWindowGeometry;
- (struct CGRect)windowWillUseStandardFrame:(id)arg1 defaultFrame:(struct CGRect)arg2;
- (BOOL)shouldCloseTabViewItem:(id)arg1;
- (void)tabView:(id)arg1 didCloseTabViewItem:(id)arg2;
- (void)setSelectedTabController:(id)arg1;
- (void)tabView:(id)arg1 didSelectTabViewItem:(id)arg2;
- (void)tabView:(id)arg1 didDropTabViewItemOutOfWindow:(struct CGPoint)arg2;
- (void)tabView:(id)arg1 draggingTabViewItemOutOfWindow:(id)arg2 toPoint:(struct CGPoint)arg3;
- (void)tabView:(id)arg1 didDragTabViewItemOutOfWindow:(id)arg2 toPoint:(struct CGPoint)arg3;
- (id)findWindowControllerAtPoint:(struct CGPoint)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (BOOL)menu:(id)arg1 updateItem:(id)arg2 atIndex:(long long)arg3 shouldCancel:(BOOL)arg4;
- (BOOL)validateMenuItem:(id)arg1;
- (BOOL)acceptsFirstResponder;
- (BOOL)windowShouldClose:(id)arg1;
- (void)displayWindowCloseSheet:(int)arg1;
- (void)closeSheetDidEnd:(id)arg1 returnCode:(int)arg2 contextInfo:(void *)arg3;
- (void)windowWillClose:(id)arg1;
- (void)windowDidBecomeMain:(id)arg1;
- (struct CGSize)windowWillResize:(id)arg1 toSize:(struct CGSize)arg2;
- (void)windowDidResize:(id)arg1;
- (void)newTab:(id)arg1;
- (void)applyProfileToAllShellsInWindow:(id)arg1;
- (id)resolveTargetTabControllerForSender:(id)arg1;
- (void)closeTab:(id)arg1;
- (void)closeOtherTabs:(id)arg1;
- (void)autoCloseSpecificTab:(id)arg1;
- (void)autoCloseAllTabs;
- (void)closeWindowIfNoMoreTabs;
- (int)countOfTabsThatNeedClosePrompt;
- (void)moveTabViewItemToNewWindow:(id)arg1;
- (void)moveTabViewItemToThisWindow:(id)arg1 fromWindowController:(id)arg2;
- (void)selectNextTab:(id)arg1;
- (void)selectPreviousTab:(id)arg1;
- (void)toggleTabBarShown:(id)arg1;
- (void)mergeAllWindows:(id)arg1;
- (void)moveTabToNewWindow:(id)arg1;
- (void)inspectTabWithController:(id)arg1;
- (void)inspectTab:(id)arg1;
- (void)splitActivePane:(id)arg1;
- (void)closeActivePane:(id)arg1;
- (id)newTabWithProfile:(id)arg1;
- (id)newTabWithProfile:(id)arg1 command:(id)arg2 runAsShell:(BOOL)arg3;
- (void)addExistingTabViewItem:(id)arg1 atPoint:(struct CGPoint)arg2;
- (void)addExistingTabViewItem:(id)arg1;
- (void)removeTabViewItem:(id)arg1;
- (void)removeTabController:(id)arg1;
- (id)tabControllers;
- (unsigned long long)numberOfTabs;
- (id)tabView;
- (id)selectedTabController;
- (void)scanForDirtyTabControllers;
- (BOOL)isBeingDragged;
- (void)setIsBeingDragged:(BOOL)arg1;
- (void)setGeometryUpdateInProgress:(BOOL)arg1;
- (BOOL)isGeometryUpdateInProgress;
- (void)setCloseDialogExpected:(BOOL)arg1;
- (BOOL)closeDialogExpected;
- (id)contextualMenu;
- (id)contextualMenuForSelection;
- (id)contextualMenuForTabItems;
- (id)contextualMenuForTabView;
- (void)settingsPickerDidSelectProfile:(id)arg1;
- (id)thumbnailOfSize:(struct CGSize)arg1 forProfile:(id)arg2;
@property BOOL hasAssignedFrame; // @synthesize hasAssignedFrame=_hasAssignedFrame;

@end

