/*
 *     Generated by class-dump 3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSWindow.h"

@interface TTWindow : NSWindow
{
    struct CGRect dragFrame;
}

- (id)initWithContentRect:(struct CGRect)arg1 styleMask:(unsigned long long)arg2 backing:(unsigned long long)arg3 defer:(BOOL)arg4;
- (void)sendEvent:(id)arg1;
- (void)selectFollowingWindow:(id)arg1 goingBackwards:(BOOL)arg2;
- (BOOL)validateMenuItem:(id)arg1;
- (void)setFrame:(struct CGRect)arg1 display:(BOOL)arg2;
- (id)frameAutosaveName;
- (BOOL)_setFrameAutosaveName:(id)arg1 changeFrame:(BOOL)arg2;
@property struct CGRect dragFrame; // @synthesize dragFrame;

@end

