/*
 *     Generated by class-dump 3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "TTWindow.h"

@interface TTWindow (Scripting)
- (id)tabControllers;
- (id)selectedTabController;
- (void)setSelectedTabController:(id)arg1;
- (BOOL)scriptFrontmost;
- (void)setScriptFrontmost:(BOOL)arg1;
- (id)scriptPosition;
- (void)setScriptPosition:(id)arg1;
- (id)scriptOrigin;
- (void)setScriptOrigin:(id)arg1;
- (id)scriptSize;
- (void)setScriptSize:(id)arg1;
- (id)scriptFrame;
- (void)setScriptFrame:(id)arg1;
- (void)setBoundsAsQDRect:(id)arg1;
- (id)handleDoScriptCommand:(id)arg1;
@end

