/*
 *     Generated by class-dump 3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSViewController.h"

@class NSButton, NSNumber;

@interface TTWorkspaceSaveViewController : NSViewController
{
    NSButton *_useAsStartupCheckbox;
    NSNumber *_savedUseAsStartup;
}

- (void)dealloc;
- (void)controlTextDidChange:(id)arg1;

@end

