/*
 *     Generated by class-dump 3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "TTWorkspaceManager.h"

@interface TTWorkspaceManager (Internal)
- (void)saveToDefaults:(id)arg1;
- (void)loadFromDefaults:(id)arg1;
@end

