/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

struct CGContext;

struct _NSPoint {
    float x;
    float y;
};

struct _NSRange {
    unsigned int location;
    unsigned int length;
};

struct _NSRect {
    struct _NSPoint origin;
    struct _NSSize size;
};

struct _NSSize {
    float width;
    float height;
};

struct _NSZone;

struct __CFURL;

struct __CFUUID;

struct fd_set {
    int fds_bits[32];
};

struct storage_list {
    TTTextStorage *_field1;
    struct storage_list *_field2;
};

typedef struct {
    unsigned int y;
    unsigned int x;
} CDAnonymousStruct8;

typedef struct {
    unsigned int _field1;
    unsigned int _field2;
    unsigned int _field3;
    char *_field4;
    unsigned int _field5;
    unsigned int _field6;
} CDAnonymousStruct2;

typedef struct {
    unsigned int line;
    unsigned int column;
} CDAnonymousStruct3;

typedef struct {
    unsigned int bold:1;
    unsigned int dim:1;
    unsigned int underline:1;
    unsigned int inverted:1;
    unsigned int blink:1;
    unsigned int invisible:1;
    unsigned int tab:1;
    unsigned int marked:1;
    unsigned int custom:1;
    unsigned int ansiForegroundColor;
    unsigned int ansiBackgroundColor;
} CDAnonymousStruct4;

typedef struct {
    unsigned int _field1;
    unsigned int _field2;
} CDAnonymousStruct5;

typedef struct {
    unsigned int _field1;
    struct {
        unsigned int :1;
        unsigned int :1;
        unsigned int :1;
        unsigned int :1;
        unsigned int :1;
        unsigned int :1;
        unsigned int :1;
        unsigned int :1;
        unsigned int :1;
        unsigned int _field1;
        unsigned int _field2;
    } _field2;
} CDAnonymousStruct6;

typedef struct {
    unsigned short _field1;
    CDAnonymousStruct1 *_field2;
    unsigned int _field3;
} CDAnonymousStruct7;

typedef struct {
} CDAnonymousStruct1;

/*
 * File: /Applications/Utilities/Terminal.app/Contents/MacOS/Terminal
 * Arch: Intel 80x86 (i386)
 */

@protocol NSCoding
- (void)encodeWithCoder:(id)fp8;
- (id)initWithCoder:(id)fp8;
@end

@protocol NSCopying
- (id)copyWithZone:(struct _NSZone *)fp8;
@end

@protocol NSTextInput
- (void)insertText:(id)fp8;
- (void)doCommandBySelector:(SEL)fp8;
- (void)setMarkedText:(id)fp8 selectedRange:(struct _NSRange)fp12;
- (void)unmarkText;
- (BOOL)hasMarkedText;
- (int)conversationIdentifier;
- (id)attributedSubstringFromRange:(struct _NSRange)fp8;
- (struct _NSRange)markedRange;
- (struct _NSRange)selectedRange;
- (struct _NSRect)firstRectForCharacterRange:(struct _NSRange)fp8;
- (unsigned int)characterIndexForPoint:(struct _NSPoint)fp8;
- (id)validAttributesForMarkedText;
@end

@protocol TTBlinking
- (void)blinker:(id)fp8 didBlink:(BOOL)fp12;
@end

@protocol TTEventEncoder
- (id)initWithController:(id)fp8;
- (id)encodeEvent:(id)fp8;
@end

@protocol TTOutputDecoder
- (id)initWithController:(id)fp8;
- (id)decodeData:(id)fp8;
- (void)softReset;
- (void)hardReset;
@end

@interface TTShell : NSObject
{
    TTTabController *_controller;
    TTProfile *_profile;
    id _target;
    SEL _action;
    int _fd;
    int _pid;
    int _shellPid;
    int _shellParentPid;
    int _ttyDevice;
    char _ptyPath[12];
    int _exitStatus;
    BOOL _childTerminated;
    BOOL _pipeClosed;
    BOOL _wasDirty;
    BOOL _isUpdatingDirty;
    char *_shellArgs[255];
    NSMutableArray *_runningProcesses;
    NSString *_frontmostProcess;
    int _frontmostProcessPID;
    NSString *_shellCommand;
    int _shellExitAction;
    BOOL _useOptionAsMetaKey;
    BOOL _deleteSendsBackspace;
    NSMutableData *_writeBuffer;
}

+ (void)initialize;
+ (id)runningShells;
+ (void)signalPipeHandler:(id)fp8;
+ (void)childDidTerminate:(id)fp8;
+ (id)pathForExecutable:(id)fp8;
- (id)initWithAction:(SEL)fp8 target:(id)fp12 profile:(id)fp16 controller:(id)fp20 customShell:(id)fp24;
- (id)description;
- (id)initShellArgs:(id)fp8;
- (void)setProfile:(id)fp8;
- (void)setShellExitActionOverride:(int)fp8;
- (void)dealloc;
- (int)pid;
- (int)fileDescriptor;
- (int)ttyDevice;
- (BOOL)isRunning;
- (void)detachTarget;
- (id)target;
- (SEL)action;
- (id)controller;
- (void)childTerminated:(int)fp8;
- (void)ioManagerDidEncounterError:(id)fp8;
- (void)processEnded;
- (void)terminate;
- (void)writeData:(id)fp8;
- (void)writeData:(id)fp8 escapingCharacters:(BOOL)fp12;
- (BOOL)isDirty;
- (id)updatedRunningProcesses;
- (id)runningProcesses;
- (id)frontmostProcess;
- (void)updateContentSize:(struct _NSSize)fp8 rowCount:(unsigned int)fp16 columnCount:(unsigned int)fp20;
- (id)exitStatusMessage:(int)fp8;
- (id)ptyPathNSString;
- (int)shellExitAction;
- (id)shellCommand;
- (void)setShouldBufferWrites:(BOOL)fp8;
- (BOOL)isBufferingWrites;

@end

@interface NSString (Terminal)
+ (id)stringWithCharacter:(unsigned short)fp8 times:(unsigned int)fp12;
+ (id)equivalentStringForMenuItem:(id)fp8;
- (id)escapedFilename;
- (id)arguments;
- (id)string;
- (id)stringByNormalizingNewlines;
@end

@interface TTWindowController : NSWindowController
{
    NSMenu *_contextualMenu;
    NSMenu *_contextualMenuForSelection;
    TTTabView *_tabView;
    NSMutableArray *_tabControllers;
    unsigned int _windowProfileID;
    TTTabController *_selectedTabController;
    TTWindowController *_draggedController;
    TTWindowController *_receiverController;
    TTTabViewItem *_draggedTab;
    BOOL _isBeingDragged;
    id _delegate;
    struct _NSRect _idealContentRect;
    BOOL _blockGeometryUpdate;
    BOOL _closeDialogExpected;
    struct _NSPoint _cascadePoint;
    BOOL _hasAssignedFrame;
}

+ (void)initialize;
- (id)initWithWindow:(id)fp8;
- (void)dealloc;
- (id)windowNibName;
- (void)awakeFromNib;
- (void)setWindowProfileID:(unsigned int)fp8;
- (unsigned int)windowProfileID;
- (void)updateTitle;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)updateAutosaveName;
- (void)updateWindowGeometry;
- (struct _NSRect)windowWillUseStandardFrame:(id)fp8 defaultFrame:(struct _NSRect)fp12;
- (BOOL)shouldCloseTabViewItem:(id)fp8;
- (void)tabView:(id)fp8 didCloseTabViewItem:(id)fp12;
- (void)setSelectedTabController:(id)fp8;
- (void)tabView:(id)fp8 didSelectTabViewItem:(id)fp12;
- (void)tabView:(id)fp8 didDropTabViewItemOutOfWindow:(struct _NSPoint)fp12;
- (void)tabView:(id)fp8 draggingTabViewItemOutOfWindow:(id)fp12 toPoint:(struct _NSPoint)fp16;
- (void)tabView:(id)fp8 didDragTabViewItemOutOfWindow:(id)fp12 toPoint:(struct _NSPoint)fp16;
- (id)findWindowControllerAtPoint:(struct _NSPoint)fp8;
- (void)observeValueForKeyPath:(id)fp8 ofObject:(id)fp12 change:(id)fp16 context:(void *)fp20;
- (BOOL)menu:(id)fp8 updateItem:(id)fp12 atIndex:(int)fp16 shouldCancel:(BOOL)fp20;
- (BOOL)validateMenuItem:(id)fp8;
- (BOOL)acceptsFirstResponder;
- (BOOL)windowShouldClose:(id)fp8;
- (void)displayWindowCloseSheet:(int)fp8;
- (void)closeSheetDidEnd:(id)fp8 returnCode:(int)fp12 contextInfo:(void *)fp16;
- (void)windowWillClose:(id)fp8;
- (void)windowDidBecomeMain:(id)fp8;
- (void)windowDidResize:(id)fp8;
- (void)newTab:(id)fp8;
- (void)applyProfileToAllShellsInWindow:(id)fp8;
- (void)closeTab:(id)fp8;
- (void)closeOtherTabs:(id)fp8;
- (void)autoCloseSpecificTab:(id)fp8;
- (void)autoCloseAllTabs;
- (void)closeWindowIfNoMoreTabs;
- (int)countOfTabsThatNeedClosePrompt;
- (void)moveTabViewItemToNewWindow:(id)fp8;
- (void)moveTabViewItemToThisWindow:(id)fp8 fromWindowController:(id)fp12;
- (void)selectNextTab:(id)fp8;
- (void)selectPreviousTab:(id)fp8;
- (void)toggleTabBarShown:(id)fp8;
- (void)mergeAllWindows:(id)fp8;
- (void)moveTabToNewWindow:(id)fp8;
- (id)newTabWithProfile:(id)fp8;
- (id)newTabWithProfile:(id)fp8 command:(id)fp12 runAsShell:(BOOL)fp16;
- (void)addExistingTabViewItem:(id)fp8 atPoint:(struct _NSPoint)fp12;
- (void)addExistingTabViewItem:(id)fp8;
- (void)removeTabViewItem:(id)fp8;
- (void)removeTabController:(id)fp8;
- (id)tabControllers;
- (unsigned int)numberOfTabs;
- (id)tabView;
- (id)selectedTabController;
- (void)scanForDirtyTabControllers;
- (BOOL)isBeingDragged;
- (void)setIsBeingDragged:(BOOL)fp8;
- (void)setBlockGeometryUpdate:(BOOL)fp8;
- (BOOL)blockGeometryUpdate;
- (void)setCloseDialogExpected:(BOOL)fp8;
- (BOOL)closeDialogExpected;
- (id)contextualMenu;
- (id)contextualMenuForSelection;
- (void)settingsPickerDidSelectProfile:(id)fp8;
- (id)thumbnailOfSize:(struct _NSSize)fp8 forProfile:(id)fp16;

@end

@interface TTEncodingConverter : NSObject <TTOutputDecoder>
{
    TTProfile *_profile;
    NSMutableData *_inputBuffer;
    int _iso2022jpCSState;
    unsigned int _stringEncoding;
}

- (id)initWithController:(id)fp8;
- (id)initWithProfile:(id)fp8;
- (void)dealloc;
- (id)profile;
- (void)setProfile:(id)fp8;
- (void)observeValueForKeyPath:(id)fp8 ofObject:(id)fp12 change:(id)fp16 context:(void *)fp20;
- (id)decodeData:(id)fp8;
- (void)softReset;
- (void)hardReset;

@end

@interface TTEncodingConverter (PrivateMethods)
- (id)alignData:(id)fp8 usingEncoding:(unsigned int)fp12;
- (id)_utf8ValidateData:(id)fp8 pushBack:(BOOL)fp12;
- (id)_iso2022jpValidateData:(id)fp8 pushBack:(BOOL)fp12;
- (id)_validateData:(id)fp8 pushBack:(BOOL)fp12 encoding:(unsigned int)fp16;
@end

@interface TTNilToEmptyStringTransformer : NSValueTransformer
{
}

+ (Class)transformedValueClass;
+ (BOOL)allowsReverseTransformation;
- (id)transformedValue:(id)fp8;
- (id)reverseTransformedValue:(id)fp8;

@end

@interface TTMappedKeysToSortedTransformer : NSValueTransformer
{
    TTKeyMapTextEscaper *_escaper;
}

+ (Class)transformedValueClass;
+ (BOOL)allowsReverseTransformation;
+ (id)localizedDescriptionForMappedKey:(id)fp8;
- (id)init;
- (void)dealloc;
- (id)transformedValue:(id)fp8;

@end

@interface TTFontToStringTransformer : NSValueTransformer
{
}

+ (Class)transformedValueClass;
+ (BOOL)allowsReverseTransformation;
- (id)transformedValue:(id)fp8;

@end

@interface TTBuiltinProfile : TTProfile
{
}

+ (id)sharedBuiltinProfile;
+ (id)defaultKeyMappings;
- (id)init;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (id)description;
- (id)name;
- (void)setName:(id)fp8;
- (void)setParentProfile:(id)fp8;
- (void)setScopeValue:(id)fp8 forKey:(id)fp12;

@end

@interface TTProfile : NSObject <NSCopying, NSCoding>
{
    NSMutableDictionary *_values;
    NSMutableSet *_observedKeys;
    TTProfile *_parentProfile;
    NSString *_name;
}

+ (id)profileKeys;
- (id)init;
- (void)dealloc;
- (id)initWithProfile:(id)fp8;
- (void)encodeWithCoder:(id)fp8;
- (id)initWithCoder:(id)fp8;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (BOOL)isEqual:(id)fp8;
- (id)description;
- (void)setParentProfile:(id)fp8;
- (id)parentProfile;
- (void)setProfile:(id)fp8;
- (id)name;
- (void)setName:(id)fp8;
- (BOOL)validateName:(id *)fp8 error:(id *)fp12;
- (id)scopeValueForKey:(id)fp8;
- (void)setScopeValue:(id)fp8 forKey:(id)fp12;
- (id)scopeValues;
- (void)setScopeValues:(id)fp8;
- (id)effectiveValues;
- (id)effectiveValueForKey:(id)fp8;
- (id)valueForUndefinedKey:(id)fp8;
- (void)setValue:(id)fp8 forUndefinedKey:(id)fp12;
- (void)addObserver:(id)fp8 forKeyPath:(id)fp12 options:(unsigned int)fp16 context:(void *)fp20;
- (void)removeObserver:(id)fp8 forKeyPath:(id)fp12;
- (void)observeValueForKeyPath:(id)fp8 ofObject:(id)fp12 change:(id)fp16 context:(void *)fp20;
- (void)stopObservingParentProfile;
- (id)propertyListRepresentation;
- (id)initWithPropertyListRepresentation:(id)fp8;
- (BOOL)setPropertyListRepresentation:(id)fp8;
- (id)encodingController;

@end

@interface TTProfile (Internal)
+ (id)archivedKeys;
- (void)validate;
@end

@interface NSColor (Terminal)
+ (id)vtBlackColor;
+ (id)vtRedColor;
+ (id)vtGreenColor;
+ (id)vtYellowColor;
+ (id)vtBlueColor;
+ (id)vtMagentaColor;
+ (id)vtCyanColor;
+ (id)vtWhiteColor;
+ (id)vtBrightBlackColor;
+ (id)vtBrightRedColor;
+ (id)vtBrightGreenColor;
+ (id)vtBrightYellowColor;
+ (id)vtBrightBlueColor;
+ (id)vtBrightMagentaColor;
+ (id)vtBrightCyanColor;
+ (id)vtBrightWhiteColor;
@end

@interface TTTermFileConverter : NSObject
{
}

+ (id)convertTermFile:(id)fp8;
+ (id)convertTermFile:(id)fp8 forceWorkspace:(BOOL)fp12;
+ (id)profileWithDefaults:(id)fp8 name:(id)fp12;
+ (id)profileWithDefaults:(id)fp8 name:(id)fp12 origin:(struct _NSPoint *)fp16 isUpperLeftOrigin:(char *)fp20;
+ (id)workspaceRepresentationWithDefaultsArray:(id)fp8 name:(id)fp12;
+ (BOOL)convertKey:(id)fp8 value:(id)fp12 profile:(id)fp16;
+ (id)convertBooleanValue:(id)fp8;
+ (id)convertIntegerValue:(id)fp8;
+ (id)convertFloatValue:(id)fp8;
+ (void)convertBackgroundImagePath:(id)fp8 profile:(id)fp12;
+ (void)convertTextColors:(id)fp8 profile:(id)fp12;
+ (void)convertNSFixedPitchFont:(id)fp8 profile:(id)fp12;
+ (void)convertCursorShape:(id)fp8 profile:(id)fp12;
+ (void)convertTitleBits:(id)fp8 profile:(id)fp12;
+ (void)convertMeta:(id)fp8 profile:(id)fp12;
+ (void)convertExecutionString:(id)fp8 profile:(id)fp12;
+ (void)convertShell:(id)fp8 profile:(id)fp12;
+ (void)convertSaveLines:(id)fp8 profile:(id)fp12;
+ (id)mappingDictionary;
+ (id)typeMappingDictionary;

@end

@interface TTUUID : NSObject <NSCopying, NSCoding>
{
    struct __CFUUID *_uuid;
    NSString *_uuidString;
}

+ (id)UUID;
- (id)init;
- (id)initWithUUIDRef:(struct __CFUUID *)fp8;
- (void)dealloc;
- (BOOL)isEqual:(id)fp8;
- (unsigned int)hash;
- (id)description;
- (void)encodeWithCoder:(id)fp8;
- (id)initWithCoder:(id)fp8;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (id)string;
- (id)stringValue;
- (struct __CFUUID *)UUIDRef;
- (int)compare:(id)fp8;

@end

@interface TTWorkspace : NSObject <NSCoding, NSCopying>
{
    NSMutableArray *_windowControllers;
    NSString *_name;
}

+ (id)propertyListForWindowAtPoint:(struct _NSPoint)fp8 withProfile:(id)fp16;
+ (id)propertyListRepresentationWithName:(id)fp8 windowRepresentations:(id)fp12;
- (id)init;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (id)name;
- (void)setName:(id)fp8;
- (void)addWindowController:(id)fp8;
- (void)removeWindowController:(id)fp8;
- (void)addWorkspace:(id)fp8;
- (id)windowControllers;
- (void)encodeWithCoder:(id)fp8;
- (id)initWithCoder:(id)fp8;
- (void)showWindows;
- (id)propertyListRepresentation;
- (id)initWithPropertyListRepresentation:(id)fp8;
- (id)propertyListForWindowController:(id)fp8;
- (id)windowControllerForPropertyList:(id)fp8;

@end

@interface TTTabViewItem : NSTabViewItem
{
    NSImage *_alertImage;
    NSCell *_labelCell;
    TTTabAlertAnimation *_alertAnimation;
    struct _NSRect _rect;
    struct _NSRect _closeRect;
    struct _NSRect _alertRect;
    BOOL _alertEnabled;
    BOOL _isBeingDraggedFromOutside;
    BOOL _willDisableAlert;
    BOOL _showCloseImage;
    BOOL _isClosing;
    BOOL _willClose;
    BOOL _isOffScreen;
    float _closingProgress;
    float _closeOpacity;
    float _isTabHighlighted;
    BOOL _isBeingDragged;
    BOOL _isBeingReordered;
    BOOL _isSpringingBack;
    float _alertFadingProgress;
    float _reorderProgress;
    float _springBackProgress;
    int _reorderState;
    int _toolTipTag;
    BOOL _isSlidingInTabBar;
}

- (id)initWithIdentifier:(id)fp8;
- (void)dealloc;
- (void)animationDidEnd:(id)fp8;
- (void)drawTabViewItem:(struct _NSRect)fp8;
- (void)removeToolTip;
- (void)_drawImage:(id)fp8 inRect:(struct _NSRect)fp12 withOpacity:(float)fp28;
- (void)_drawLabel:(struct _NSRect)fp8;
- (struct _NSRect)_determineRectForImage:(id)fp8;
- (void)setIsBeingDragged:(BOOL)fp8;
- (BOOL)isBeingDragged;
- (void)setIsSpringingBack:(BOOL)fp8;
- (float)closingProgress;
- (BOOL)isSpringingBack;
- (void)setState:(unsigned int)fp8;
- (void)setIsBeingReordered:(BOOL)fp8;
- (void)setIsOffScreen:(BOOL)fp8;
- (BOOL)isOffScreen;
- (BOOL)isTabHighlighted;
- (void)setReorderState:(int)fp8;
- (int)reorderState;
- (void)setSpringBackProgress:(float)fp8;
- (float)springBackProgress;
- (void)setReorderProgress:(float)fp8;
- (float)reorderProgress;
- (void)setWillClose:(BOOL)fp8;
- (BOOL)willClose;
- (void)setAlertFadingProgress:(float)fp8;
- (float)alertFadingProgress;
- (void)setAlertImage:(id)fp8;
- (void)setShowCloseImage:(BOOL)fp8;
- (void)setIsBeingDraggedFromOutside:(BOOL)fp8;
- (BOOL)isBeingDraggedFromOutside;
- (struct _NSRect)rect;
- (struct _NSRect)closeRect;
- (void)setIsSlidingInTabBar:(BOOL)fp8;
- (BOOL)isSlidingInTabBar;
- (void)disableAlert;
- (void)enableAlert;
- (void)lightenTab;
- (void)darkenTab;
- (void)lightenCloseImage;
- (void)darkenCloseImage;
- (void)darkenMoreCloseImage;
- (BOOL)accessibilityIsIgnored;

@end

@interface TTTabAlertAnimation : TTTabAnimation
{
}

- (void)setCurrentProgress:(float)fp8;

@end

@interface TTTabAnimation : NSAnimation
{
    TTTabViewItem *_tab;
}

- (id)tab;
- (void)setTab:(id)fp8;

@end

@interface TTTabView : NSTabView
{
    struct _NSRect _overflowImageRect;
    struct _NSRect _tabFrame;
    TTTabViewItem *_draggedTab;
    TTTabViewItem *_draggedTabOnCloseImage;
    unsigned int _draggedTabInitialIndex;
    struct _NSPoint _lastMouseDownLocation;
    float _tabDraggedXOffset;
    float _tabDraggedYOffset;
    float _tabDraggedXOffsetBeyondBounds;
    BOOL _showOverflowTabMenu;
    BOOL _isShowingOverflowMenu;
    BOOL _isMouseOffScreen;
    BOOL _isTabViewOnBottom;
    BOOL _showTabIfOnlyOne;
    BOOL _isRegisteredForDragEvents;
    NSImage *_overflowTabMenuImage;
    NSImage *_draggingImage;
    float TT_TAB_FRAME_BOTTOM;
    NSAnimation *_activeAnimation;
}

- (id)initWithFrame:(struct _NSRect)fp8;
- (void)dealloc;
- (void)initTabFrame;
- (void)setFrame:(struct _NSRect)fp8;
- (void)viewWillMoveToWindow:(id)fp8;
- (void)windowDidChangeKey:(id)fp8;
- (BOOL)acceptsMouseMovedEvents;
- (BOOL)acceptsFirstResponder;
- (id)tabViewItemAtPoint:(struct _NSPoint)fp8;
- (void)mouseDown:(id)fp8;
- (void)mouseUp:(id)fp8;
- (void)mouseMoved:(id)fp8;
- (void)mouseDragged:(id)fp8;
- (void)draggedImage:(id)fp8 endedAt:(struct _NSPoint)fp12 operation:(unsigned int)fp20;
- (void)draggedImage:(id)fp8 movedTo:(struct _NSPoint)fp12;
- (struct _NSPoint)recenterMouseInFloatingTab:(struct _NSPoint)fp8;
- (struct _NSPoint)reverseRecenterMouseInFloatingTab:(struct _NSPoint)fp8;
- (void)registerForDragEvents;
- (void)unregisterForDragEvents;
- (BOOL)isValidDragOperation:(id)fp8;
- (BOOL)prepareForDragOperation:(id)fp8;
- (BOOL)performDragOperation:(id)fp8;
- (unsigned int)draggingEntered:(id)fp8;
- (unsigned int)draggingUpdated:(id)fp8;
- (void)draggingExited:(id)fp8;
- (void)selectTabViewItem:(id)fp8;
- (void)selectNextTabViewItem:(id)fp8;
- (void)selectPreviousTabViewItem:(id)fp8;
- (void)removeTabViewItem:(id)fp8;
- (void)addTabViewItem:(id)fp8;
- (void)addTabViewItem:(id)fp8 atPoint:(struct _NSPoint)fp12;
- (BOOL)isTabViewItemInOverflowMenu:(id)fp8;
- (int)indexOfLastVisibleTabViewItem;
- (void)stopActiveAnimation;
- (void)startTabReorderAnimation:(id)fp8;
- (void)startSpringBackAnimation:(id)fp8;
- (void)animationDidEnd:(id)fp8;
- (struct _NSRect)rectForTabViewItemForNumberOfTabs:(int)fp8;
- (struct _NSRect)contentRect;
- (struct _NSSize)frameSizeForContentSize:(struct _NSSize)fp8;
- (struct _NSSize)contentSizeForFrameSize:(struct _NSSize)fp8;
- (void)removeTabViewTooltips;
- (struct _NSRect)_tabRectAdjustedForOverlap:(struct _NSRect)fp8;
- (struct _NSRect)resizeRectToFitInsideBounds:(struct _NSRect)fp8;
- (void)viewDidEndLiveResize;
- (void)resizeWindowToAccountForTabsBeingDisplayed:(int)fp8;
- (void)drawTabOverflowMenuImage;
- (void)drawBorderAndBackground;
- (void)drawRect:(struct _NSRect)fp8;
- (BOOL)menu:(id)fp8 updateItem:(id)fp12 atIndex:(int)fp16 shouldCancel:(BOOL)fp20;
- (void)menuNeedsUpdate:(id)fp8;
- (void)selectTabFromMenu:(id)fp8;
- (id)lineColor;
- (BOOL)isFlipped;
- (void)setTabViewOnBottom:(BOOL)fp8;
- (BOOL)tabViewOnBottom;
- (void)setShowTabIfOnlyOne:(BOOL)fp8;
- (BOOL)showTabIfOnlyOne;
- (id)selectedTabViewItem;
- (struct _NSRect)tabFrame;
- (void)setTabDraggedXOffset:(float)fp8;
- (float)tabDraggedXOffset;
- (float)tabDraggedYOffset;
- (void)setDraggedTab:(id)fp8;
- (id)draggedTab;
- (void)setOverflowTabMenuImage:(id)fp8;
- (id)view:(id)fp8 stringForToolTip:(int)fp12 point:(struct _NSPoint)fp16 userData:(void *)fp24;
- (BOOL)accessibilityIsIgnored;

@end

@interface NSTabView (TTTabExtension)
- (void)exchangeItemAtIndex:(int)fp8 withItemAtIndex:(int)fp12;
- (struct _NSRect)expandRect:(struct _NSRect)fp8;
@end

@interface TTTabReorderAnimation : TTTabAnimation
{
}

- (void)setCurrentProgress:(float)fp8;

@end

@interface TTTabController : NSObject
{
    TTTabViewItem *_tab;
    TTView *_view;
    NSScroller *_scroller;
    NSBox *_contentView;
    TTShell *_shell;
    TTLogicalScreen *_logicalScreen;
    NSObject<TTOutputDecoder> *_outputDecoder;
    NSObject<TTOutputDecoder> *_encodingConverter;
    NSObject<TTEventEncoder> *_eventEncoder;
    TTProfile *_profile;
    NSFont *_customFont;
    NSString *_customTitle;
    TTProfile *_scriptingProfile;
}

+ (void)initialize;
- (id)init;
- (id)initWithProfile:(id)fp8 command:(id)fp12 runAsShell:(BOOL)fp16;
- (void)setProfile:(id)fp8;
- (void)setGeometryToProfile:(id)fp8;
- (void)dealloc;
- (void)setTab:(id)fp8;
- (id)getTabViewItem;
- (id)getWindowController;
- (BOOL)tabShouldClose;
- (void)closeSheetDidEnd:(id)fp8 returnCode:(int)fp12 contextInfo:(void *)fp16;
- (void)shellDidReceiveData:(id)fp8;
- (id)outputDecoder;
- (id)encodingConverter;
- (id)eventEncoder;
- (id)logicalScreen;
- (id)profile;
- (id)shell;
- (void)initViews;
- (id)view;
- (id)scroller;
- (id)contentView;
- (id)title;
- (id)tabTitle;
- (id)customFont;
- (void)setCustomFont:(id)fp8;
- (void)setCustomFontOverride:(id)fp8;
- (id)customTitle;
- (void)setCustomTitle:(id)fp8;
- (void)scrollToTop;
- (void)scrollToBottom;
- (void)lineUp;
- (void)lineDown;
- (void)pageUp;
- (void)pageDown;
- (void)updateFromScroller:(id)fp8;
- (BOOL)needsClosePrompt;
- (void)reapShell:(BOOL)fp8;
- (void)writeDirectToScreen:(id)fp8;
- (void)observeValueForKeyPath:(id)fp8 ofObject:(id)fp12 change:(id)fp16 context:(void *)fp20;
- (void)emulatorDidDecodeData:(id)fp8;

@end

@interface TTTabSpringBackAnimation : TTTabAnimation
{
}

- (void)setCurrentProgress:(float)fp8;

@end

@interface TTWindow : NSWindow
{
    struct _NSRect _fullFrame;
}

- (id)initWithContentRect:(struct _NSRect)fp8 styleMask:(unsigned int)fp24 backing:(unsigned int)fp28 defer:(BOOL)fp32;
- (void)sendEvent:(id)fp8;
- (void)selectFollowingWindow:(id)fp8 goingBackwards:(BOOL)fp12;
- (struct _NSRect)fullFrame;
- (void)setFullFrame:(struct _NSRect)fp8;
- (BOOL)validateMenuItem:(id)fp8;

@end

@interface TTShellReaper : NSObject
{
    NSMutableArray *_shellArray;
    NSThread *_thread;
    NSConditionLock *_conditionLock;
}

+ (id)sharedReaper;
- (id)init;
- (void)dealloc;
- (void)reapShell:(id)fp8;
- (void)reapShellsInArray:(id)fp8;
- (void)wait;
- (void)grimReaper;

@end

@interface TTBlinker : NSObject
{
    NSTimer *_timer;
    NSMutableSet *_targets;
    BOOL _flag;
    BOOL _isHidden;
    BOOL _isSessionActive;
}

+ (id)sharedBlinker;
- (id)init;
- (void)dealloc;
- (void)addTarget:(id)fp8;
- (void)removeTarget:(id)fp8;
- (BOOL)containsTarget:(id)fp8;
- (void)dispatchBlink:(id)fp8;
- (void)applicationDidUnhide:(id)fp8;
- (void)applicationDidHide:(id)fp8;
- (void)sessionDidBecomeActive:(id)fp8;
- (void)sessionDidResignActive:(id)fp8;
- (void)updateTimer;

@end

@interface TTLogicalScreen : NSObject
{
    TTProfile *_profile;
    unsigned int _columnCount;
    unsigned int _rowCount;
    struct _NSRange _scrollRange;
    CDAnonymousStruct3 _cursorPosition;
    TTTextStorageManager *_scrollbackStorage;
    TTActiveTextStorage *_activeStorage;
    BOOL _isInverted;
    BOOL _isCursorVisible;
    BOOL _isAlternateScreenActive;
    TTActiveTextStorage *_savedActiveStorage;
    CDAnonymousStruct3 _savedCursorPosition;
    BOOL _isResizing;
    unsigned int _resizeDepth;
    unsigned int _savedRowCount;
    unsigned int _savedCursorOffset;
    NSMutableIndexSet *_doubleHighTopLines;
    NSMutableIndexSet *_doubleHighBottomLines;
    NSMutableIndexSet *_doubleWideLines;
    CDAnonymousStruct2 *_unicharOffsetCache;
    unsigned int _unicharOffsetCacheCursorOffset;
    unsigned int _unicharOffsetCacheCursorLine;
    CDAnonymousStruct2 *_unicharOffsetCacheUTF8Buffer;
    CDAnonymousStruct2 *_unicharOffsetCacheUTF16Buffer;
    CDAnonymousStruct2 *_unicharOffsetCacheRunBuffer;
    unsigned int _unicharOffsetCacheGenerationNumber;
    TTLogicalScreenString *_unicharOffsetCacheString;
    NSMutableIndexSet *_dirtyLines;
    BOOL _isBlitSafe;
}

+ (BOOL)automaticallyNotifiesObserversForKey:(id)fp8;
- (id)initWithProfile:(id)fp8 columnCount:(unsigned int)fp12 rowCount:(unsigned int)fp16;
- (void)dealloc;
- (id)profile;
- (void)setProfile:(id)fp8;
- (id)scrollbackStorage;
- (unsigned int)rowCount;
- (void)setRowCount:(unsigned int)fp8;
- (unsigned int)columnCount;
- (void)setColumnCount:(unsigned int)fp8;
- (unsigned int)lineCount;
- (void)beginResizeOperation;
- (void)endResizeOperation;
- (void)setRowCount:(unsigned int)fp8 columnCount:(unsigned int)fp12;
- (struct _NSSize)contentSize;
- (CDAnonymousStruct5)cursorPosition;
- (void)setCursorPosition:(CDAnonymousStruct5)fp8;
- (CDAnonymousStruct5)displayCursorPosition;
- (unsigned int)cursorLine;
- (void)setCursorLine:(unsigned int)fp8;
- (unsigned int)cursorColumn;
- (void)setCursorColumn:(unsigned int)fp8;
- (void)setCursorRowWrapped:(BOOL)fp8;
- (BOOL)isCursorRowWrapped;
- (unsigned int)logicalWidthForLine:(unsigned int)fp8;
- (struct _NSRange)lineRangeForLine:(unsigned int)fp8;
- (unsigned int)sizeForLine:(unsigned int)fp8;
- (unsigned int)cursorLineSize;
- (void)setSize:(unsigned int)fp8 forLine:(unsigned int)fp12;
- (void)setCursorLineSize:(unsigned int)fp8;
- (CDAnonymousStruct5)insertUTF8Characters:(const char *)fp8 length:(unsigned int)fp12 withAttributes:(CDAnonymousStruct4)fp16 atPosition:(CDAnonymousStruct5)fp28;
- (CDAnonymousStruct5)overwriteUTF8Characters:(const char *)fp8 length:(unsigned int)fp12 withAttributes:(CDAnonymousStruct4)fp16 atPosition:(CDAnonymousStruct5)fp28;
- (void)deleteUTF8Characters:(unsigned int)fp8 atPosition:(CDAnonymousStruct5)fp12;
- (void)deleteAndReverseWrapUTF8Characters:(unsigned int)fp8 atPosition:(CDAnonymousStruct5)fp12;
- (void)deleteUTF8CharactersInLineRange:(struct _NSRange)fp8;
- (void)shiftLineRange:(struct _NSRange)fp8 inDirection:(unsigned int)fp16 byAmount:(unsigned int)fp20;
- (void)truncateScrollbackFromBeginningToLineLength:(unsigned int)fp8;
- (BOOL)isAlternateScreenActive;
- (void)setAlternateScreenActive:(BOOL)fp8;
- (BOOL)isInverted;
- (void)setInverted:(BOOL)fp8;
- (BOOL)isCursorVisible;
- (void)setCursorVisible:(BOOL)fp8;
- (void)setAutoWrap:(BOOL)fp8;
- (BOOL)autoWrap;
- (struct _NSRange)scrollRange;
- (void)setScrollRange:(struct _NSRange)fp8;
- (void)getLine:(unsigned int)fp8 UTF8Characters:(CDAnonymousStruct2 *)fp12 runs:(CDAnonymousStruct2 *)fp16;
- (unsigned int)displayWidthForCharacter:(int)fp8;
- (unsigned int)logicalWidthForCharacter:(int)fp8;
- (void)setBlitSafe:(BOOL)fp8;
- (BOOL)isBlitSafe;
- (void)observeValueForKeyPath:(id)fp8 ofObject:(id)fp12 change:(id)fp16 context:(void *)fp20;
- (void)clearScrollback;
- (void)pullLinesFromScrollback:(unsigned int)fp8 toActiveStorage:(id)fp12 scanningForEmptyLines:(unsigned int)fp16;

@end

@interface TTTextStorage : NSObject
{
    CDAnonymousStruct2 *_chars;
    CDAnonymousStruct2 *_runs;
    CDAnonymousStruct2 *_lineOffsets;
    BOOL _isTextWrapped;
    unsigned int _columnCount;
}

- (id)initWithColumnCount:(unsigned int)fp8;
- (void)reinitializeWithColumnCount:(unsigned int)fp8;
- (void)dealloc;
- (id)description;
- (BOOL)isTextWrapped;
- (void)setTextWrapped:(BOOL)fp8;
- (unsigned int)columnCount;
- (unsigned int)length;
- (CDAnonymousStruct2 *)chars;
- (CDAnonymousStruct2 *)runs;
- (CDAnonymousStruct2 *)lineOffsets;
- (void)setLineOffsets:(CDAnonymousStruct2 *)fp8;
- (CDAnonymousStruct6 *)firstRunAtLineOffset:(unsigned int)fp8 returnIndex:(unsigned int *)fp12;
- (void)getLine:(unsigned int)fp8 UTF8Characters:(CDAnonymousStruct2 *)fp12 runs:(CDAnonymousStruct2 *)fp16;
- (void)appendUTF8Characters:(const char *)fp8 length:(unsigned int)fp12 withAttributes:(CDAnonymousStruct4)fp16 doesBeginLine:(BOOL)fp28;
- (void)truncateToCharacterLength:(unsigned int)fp8;
- (void)truncateToLineLength:(unsigned int)fp8;
- (void)deleteLinesFromBeginning:(unsigned int)fp8;
- (unsigned int)wrapToColumnCount:(unsigned int)fp8 startingAtColumn:(unsigned int)fp12 withLogicalScreen:(id)fp16;
- (unsigned int)wrapLineOffsets:(CDAnonymousStruct2 *)fp8 toColumnCount:(unsigned int)fp12 startingAtColumn:(unsigned int)fp16 withLogicalScreen:(id)fp20;

@end

@interface TTPrintingView : TTView
{
}

- (unsigned int)rowCount;

@end

@interface TTView : TTAccessibleView <TTBlinking, NSTextInput>
{
    struct _NSSize _cellSize;
    float _descender;
    float _leading;
    float _baselineOffset;
    TTLogicalScreen *_logicalScreen;
    TTProfile *_profile;
    TTTabController *_controller;
    NSTimer *_needsDisplayTimer;
    BOOL _shouldUpdateDirtyFlag;
    BOOL _isDrawingThumbnail;
    CDAnonymousStruct2 *_glyphsBuffer;
    CDAnonymousStruct2 *_advancesBuffer;
    CDAnonymousStruct2 *_indicesBuffer;
    BOOL _isTextBlinkActive;
    BOOL _isCursorBlinkActive;
    BOOL _shouldSuppressCursorBlink;
    BOOL _isVisualBellActive;
    BOOL _doRectangularSelection;
    BOOL _doAppendSelection;
    BOOL _doDiscontinuousSelection;
    BOOL _doPathOrURLSelection;
    unsigned int _selectionStyle;
    BOOL _isTransientSelection;
    BOOL _isDraggingSelection;
    BOOL _isPrintable;
    BOOL _isHandlingContextualMenu;
    NSMenuItem *_openURLMenuItem;
    NSURL *_contextualMenuURL;
    NSMutableIndexSet *_activeTextSelection;
    NSMutableIndexSet *_textSelectionRanges;
    NSMutableIndexSet *_selectionSetDifference;
    NSMutableIndexSet *_savedTextSelectionRanges;
    CDAnonymousStruct8 _initialSelectionPoint;
    CDAnonymousStruct8 _endSelectionPoint;
    CDAnonymousStruct8 _previousSelectionStart;
    CDAnonymousStruct8 _previousSelectionEnd;
    NSCursor *_mouseCursor;
    BOOL _dragAndDropIsActive;
    unsigned int _printRange;
    CDAnonymousStruct3 _ttaxLastCursorPosition;
    unsigned int _ttaxLastLineCount;
    BOOL _hasMarkedText;
    BOOL _markedTextHasAttributes;
    NSAttributedString *_markedText;
    CDAnonymousStruct3 _markedTextAnchor;
    unsigned int _markedTextWidth;
    BOOL _hasUnprocessedInsertion;
    NSInvocation *_markedTextInvocation;
    NSMutableIndexSet *_dirtyLines;
    BOOL _shouldDirtyAllLines;
    NSMutableIndexSet *_blinkingLines;
    unsigned int _scrollingLineOffset;
    BOOL _isScrollingPinned;
    NSImage *_backgroundImage;
    unsigned int _alertSoundID;
    unsigned int _alertQueueCount;
}

+ (void)initialize;
+ (struct _NSRect)unpaddedContentRectForProfile:(id)fp8;
+ (struct _NSSize)logicalContentSizeForRect:(struct _NSRect)fp8 profile:(id)fp24 controller:(id)fp28;
+ (id)markedTextAttributes;
+ (id)trustedFontNames;
+ (struct _NSSize)cellSizeForProfile:(id)fp8 controller:(id)fp12;
+ (struct _NSRect)rectWithoutPadding:(struct _NSRect)fp8;
- (id)initWithFrame:(struct _NSRect)fp8;
- (void)dealloc;
- (id)controller;
- (void)setController:(id)fp8;
- (id)profile;
- (void)setProfile:(id)fp8;
- (void)setObserversForLogicalScreen:(BOOL)fp8;
- (id)logicalScreen;
- (void)setLogicalScreen:(id)fp8;
- (void)screenDidRewrap:(id)fp8;
- (id)string;
- (struct _NSSize)cellSize;
- (struct _NSSize)contentSize;
- (struct _NSSize)contentSizeForLogicalContentSize:(struct _NSSize)fp8;
- (struct _NSRect)unpaddedContentRect;
- (void)updateShellContentSize;
- (void)sizeToFit:(struct _NSRect)fp8;
- (BOOL)isOpaque;
- (BOOL)preservesContentDuringLiveResize;
- (void)viewDidEndLiveResize;
- (struct _NSRange)lineRangeForRect:(struct _NSRect)fp8;
- (void)drawRect:(struct _NSRect)fp8;
- (void)drawAttributedStringsToScreen:(BOOL)fp8 inRect:(struct _NSRect)fp12 selectedTextRanges:(id)fp28 selectionColor:(id)fp32;
- (void)drawAttributedString:(id)fp8 forLine:(unsigned int)fp12 inContext:(struct CGContext *)fp16 atPoint:(struct _NSPoint)fp20 isTextMarked:(BOOL)fp28 size:(unsigned int)fp32 containsCursor:(BOOL)fp36 atColumn:(unsigned int)fp40 selectedTextRanges:(id)fp44 selectionColor:(id)fp48;
- (void)drawCustomString:(id)fp8 inContext:(struct CGContext *)fp12 atPoint:(struct _NSPoint)fp16;
- (void)drawCursor;
- (id)colorForANSIColor:(unsigned int)fp8;
- (void)clearScrollback:(id)fp8;
- (void)scrollToBeginningOfDocument:(id)fp8;
- (void)scrollToEndOfDocument:(id)fp8;
- (void)scrollToTop:(id)fp8;
- (void)scrollToBottom:(id)fp8;
- (void)lineUp:(id)fp8;
- (void)lineDown:(id)fp8;
- (void)scrollPageUp:(id)fp8;
- (void)scrollPageDown:(id)fp8;
- (void)pageUp:(id)fp8;
- (void)pageDown:(id)fp8;
- (void)printTerminal:(id)fp8;
- (void)printTerminalSelection:(id)fp8;
- (void)runPrintTerminalOperation;
- (void)setProfileAsDefault:(id)fp8;
- (void)saveProfile:(id)fp8;
- (void)saveProfileAndSetAsDefault:(id)fp8;
- (void)saveProfileAsDefault:(BOOL)fp8;
- (void)profileSavePanelDidEnd:(id)fp8 returnCode:(int)fp12;
- (void)saveProfileImmediately:(id)fp8;
- (void)applyFrontMostWindowProfileToAllShells:(id)fp8;
- (void)restoreFactoryDefaultProfile:(id)fp8;
- (void)takeProfileFrom:(id)fp8;
- (void)setPickedProfile:(id)fp8;
- (void)performTerminalFindPanelAction:(id)fp8;
- (void)centerSelectionInVisibleArea:(id)fp8;
- (void)returnToDefaultSize:(id)fp8;
- (void)searchInSpotlight:(id)fp8;
- (void)searchInGoogle:(id)fp8;
- (void)lookUpInDictionary:(id)fp8;
- (void)selectTitleField:(id)fp8;
- (BOOL)acceptsFirstResponder;
- (BOOL)_wantsKeyDownForEvent:(id)fp8;
- (void)keyDown:(id)fp8;
- (void)cancelOperation:(id)fp8;
- (void)deleteBackward:(id)fp8;
- (BOOL)performKeyEquivalent:(id)fp8;
- (void)cursorUpdate:(id)fp8;
- (id)menuForEvent:(id)fp8;
- (void)openURL:(id)fp8;
- (void)viewWillMoveToWindow:(id)fp8;
- (void)viewDidMoveToWindow;
- (void)windowDidChangeMain:(id)fp8;
- (void)emulatorDidDecodeData:(id)fp8;
- (void)emulatorDidBeep:(id)fp8;
- (void)needsDisplayTimer:(id)fp8;
- (void)blinker:(id)fp8 didBlink:(BOOL)fp12;
- (void)changeFont:(id)fp8;
- (void)observeValueForKeyPath:(id)fp8 ofObject:(id)fp12 change:(id)fp16 context:(void *)fp20;
- (void)updateBlinker;
- (BOOL)isInverted;
- (CDAnonymousStruct2 *)createUTF16FromUTF8:(CDAnonymousStruct2 *)fp8;
- (void)setPrintRange:(unsigned int)fp8;
- (unsigned int)printRange;
- (void)setPrintable:(BOOL)fp8;
- (unsigned int)rowCount;
- (struct _NSRect)boundsForPrintRange:(unsigned int)fp8;
- (struct _NSRange)lineRangeForPrintRange:(unsigned int)fp8;
- (struct _NSSize)effectivePageSize;
- (struct _NSSize)unscaledEffectivePageSize;
- (void)beginPageInRect:(struct _NSRect)fp8 atPlacement:(struct _NSPoint)fp24;
- (BOOL)knowsPageRange:(struct _NSRange *)fp8;
- (struct _NSRect)rectForPage:(int)fp8;
- (void)printOperationDidRun:(id)fp8 success:(BOOL)fp12 contextInfo:(void *)fp16;
- (void)saveTextAs:(id)fp8;
- (void)saveSelectedTextAs:(id)fp8;
- (void)savePanelDidEnd:(id)fp8 returnCode:(int)fp12 contextInfo:(void *)fp16;
- (void)didPresentSaveErrorWithRecovery:(BOOL)fp8 contextInfo:(void *)fp12;
- (void)exportSettings:(id)fp8;
- (void)exportPanelDidEnd:(id)fp8 returnCode:(int)fp12 contextInfo:(void *)fp16;
- (void)selectAll:(id)fp8;
- (void)sendSoftReset:(id)fp8;
- (void)sendHardReset:(id)fp8;
- (id)allText;
- (id)selectedText;
- (id)selectedTextParagraphCounts;
- (void)copySelectedText:(id)fp8;
- (void)copy:(id)fp8;
- (void)paste:(id)fp8;
- (void)pasteSelection:(id)fp8;
- (void)pasteEscaped:(id)fp8;
- (BOOL)pasteboardHasText;
- (BOOL)validateMenuItem:(id)fp8;
- (BOOL)readSelectionFromPasteboard:(id)fp8;
- (BOOL)readSelectionFromPasteboard:(id)fp8 isDragAndDrop:(BOOL)fp12;
- (BOOL)readSelectionFromString:(id)fp8;
- (BOOL)writeSelectionToPasteboard:(id)fp8 types:(id)fp12;
- (id)validRequestorForSendType:(id)fp8 returnType:(id)fp12;
- (void)flagsChanged:(id)fp8;
- (void)mouseDown:(id)fp8;
- (void)mouseUp:(id)fp8;
- (void)mouseDragged:(id)fp8;
- (void)mouseEntered:(id)fp8;
- (void)otherMouseDown:(id)fp8;
- (void)scrollWheel:(id)fp8;
- (void)scrollLinesBy:(int)fp8;
- (void)scrollLinesTo:(unsigned int)fp8;
- (void)updateScroller;
- (void)autoscroll:(id)fp8;
- (unsigned int)draggingSourceOperationMaskForLocal:(BOOL)fp8;
- (unsigned int)draggingEntered:(id)fp8;
- (unsigned int)draggingUpdated:(id)fp8;
- (void)draggingExited:(id)fp8;
- (BOOL)performDragOperation:(id)fp8;
- (void)concludeDragOperation:(id)fp8;
- (void)insertText:(id)fp8;
- (void)doCommandBySelector:(SEL)fp8;
- (void)setMarkedText:(id)fp8 selectedRange:(struct _NSRange)fp12;
- (void)unmarkText;
- (BOOL)hasMarkedText;
- (int)conversationIdentifier;
- (id)attributedSubstringFromRange:(struct _NSRange)fp8;
- (struct _NSRange)markedRange;
- (struct _NSRange)selectedRange;
- (struct _NSRect)firstRectForCharacterRange:(struct _NSRange)fp8;
- (unsigned int)characterIndexForPoint:(struct _NSPoint)fp8;
- (id)validAttributesForMarkedText;
- (void)removeMarkedText;
- (id)NSRectArrayForRanges:(id)fp8;
- (id)NSRectArrayForRange:(struct _NSRange)fp8;
- (struct _NSRect)rectForLineRange:(struct _NSRange)fp8;
- (id)bezierPathForRanges:(id)fp8;
- (id)bezierPathForRanges:(id)fp8 intersectingRect:(struct _NSRect)fp12;
- (void)delayedSetNeedsDisplayInLine:(unsigned int)fp8;
- (void)delayedSetNeedsDisplayInLines:(id)fp8;
- (void)scheduleDelayedDisplayTimer:(BOOL)fp8;
- (void)delayedSetNeedsDisplay:(BOOL)fp8;
- (void)setNeedsDisplayInRanges:(id)fp8;
- (void)setNeedsImmediateDisplay;
- (void)calculateCellSize;
- (void)drawSelectedTextRanges:(id)fp8 withColor:(id)fp12;
- (struct _NSPoint)pointForDisplayPosition:(CDAnonymousStruct5)fp8;
- (CDAnonymousStruct5)displayPositionForPoint:(struct _NSPoint)fp8;
- (void)handleAlertCompletion;

@end

@interface TTActiveTextStorage : NSObject
{
    CDAnonymousStruct2 *_lines;
    unsigned int _rowCount;
    unsigned int _columnCount;
    TTLogicalScreen *_screen;
    NSMutableIndexSet *_wrappedIndices;
    BOOL _isWrappingEnabled;
}

- (id)initWithLogicalScreen:(id)fp8 columnCount:(unsigned int)fp12 rowCount:(unsigned int)fp16;
- (void)dealloc;
- (unsigned int)rowCount;
- (void)setRowCount:(unsigned int)fp8;
- (unsigned int)columnCount;
- (void)setColumnCount:(unsigned int)fp8;
- (BOOL)isWrappingEnabled;
- (void)setWrappingEnabled:(BOOL)fp8;
- (void)setWrappedFlag:(BOOL)fp8 forLine:(unsigned int)fp12;
- (BOOL)wrappedFlagForLine:(unsigned int)fp8;
- (unsigned int)sizeForLine:(unsigned int)fp8;
- (void)setSize:(unsigned int)fp8 forLine:(unsigned int)fp12;
- (CDAnonymousStruct5)insertUTF8Characters:(const char *)fp8 length:(unsigned int)fp12 withAttributes:(CDAnonymousStruct4)fp16 atPosition:(CDAnonymousStruct5)fp28;
- (CDAnonymousStruct5)overwriteUTF8Characters:(const char *)fp8 length:(unsigned int)fp12 withAttributes:(CDAnonymousStruct4)fp16 atPosition:(CDAnonymousStruct5)fp28;
- (void)deleteUTF8Characters:(unsigned int)fp8 atPosition:(CDAnonymousStruct5)fp12;
- (void)deleteAndReverseWrapUTF8Characters:(unsigned int)fp8 atPosition:(CDAnonymousStruct5)fp12;
- (void)deleteCharactersInLineRange:(struct _NSRange)fp8;
- (void)shiftLineRange:(struct _NSRange)fp8 inDirection:(unsigned int)fp16 byAmount:(unsigned int)fp20;
- (void)moveToStorageManager:(id)fp8;
- (void)shiftLineRangeUpToScrollback:(struct _NSRange)fp8 byAmount:(unsigned int)fp16;
- (unsigned int)truncateLength:(unsigned int)fp8 ofString:(const char *)fp12 toColumnCount:(unsigned int)fp16;
- (unsigned int)widthOfString:(const char *)fp8 length:(unsigned int)fp12;
- (void)getLine:(unsigned int)fp8 UTF8Characters:(CDAnonymousStruct2 *)fp12 runs:(CDAnonymousStruct2 *)fp16;
- (id)attributedStringForLine:(unsigned int)fp8;

@end

@interface TTAttributedString : NSObject
{
    CDAnonymousStruct2 *_chars;
    CDAnonymousStruct2 *_runs;
    unsigned int _width;
    unsigned int _insertionColumn;
    unsigned int _insertionCharOffset;
    unsigned int _insertionRunIndex;
    unsigned int _insertionRunOffset;
    TTLogicalScreen *_screen;
    unsigned int _size;
}

- (id)initWithLogicalScreen:(id)fp8;
- (void)dealloc;
- (id)description;
- (unsigned int)width;
- (void)updateWidth;
- (unsigned int)size;
- (void)setSize:(unsigned int)fp8;
- (CDAnonymousStruct2 *)chars;
- (CDAnonymousStruct2 *)runs;
- (void)insertUTF8Characters:(const char *)fp8 length:(unsigned int)fp12 width:(unsigned int)fp16 withAttributes:(CDAnonymousStruct4)fp20 atColumn:(unsigned int)fp32;
- (void)overwriteUTF8Characters:(const char *)fp8 length:(unsigned int)fp12 width:(unsigned int)fp16 withAttributes:(CDAnonymousStruct4)fp20 atColumn:(unsigned int)fp32;
- (void)deleteCharactersInColumnRange:(struct _NSRange)fp8;
- (void)deleteAllCharacters;
- (void)appendToStorageManager:(id)fp8 withNewline:(BOOL)fp12;
- (void)advanceInsertionPointToColumn:(unsigned int)fp8 fillingSpaceIfNecessary:(BOOL)fp12;
- (void)validate;
- (void)getUTF8Characters:(CDAnonymousStruct2 *)fp8 runs:(CDAnonymousStruct2 *)fp12;

@end

@interface TTVT100Emulator : NSObject <TTEventEncoder, TTOutputDecoder>
{
    unsigned int _state;
    TTLogicalScreen *_logicalScreen;
    TTShell *_shell;
    TTProfile *_profile;
    TTTabController *_controller;
    unsigned int *_stateTable;
    unsigned int *_defaultBaseStateTable;
    BOOL _screenSavedWrapState;
    unsigned int _numParams;
    int _params[32];
    NSMutableString *_operatingSystemCommand;
    struct _NSRange _scrollRange;
    BOOL _isScrollRangeActive;
    BOOL _isCursorInMargin;
    BOOL _isCursorSaved;
    struct {
        unsigned int cursorRow;
        unsigned int cursorColumn;
        unsigned int alternateCursorRow;
        unsigned int alternateCursorColumn;
        CDAnonymousStruct4 attributes;
        char scrollRegionOrigin;
        unsigned int rowCount;
        CDAnonymousStruct1 *translationTable[5][128];
    } _savedCursorState;
    struct {
        unsigned int linefeedNewline:1;
        unsigned int scrollRegionOrigin:1;
        unsigned int autoWrap:1;
        unsigned int reverseLineWrap:1;
        unsigned int keyboardAction:1;
        unsigned int autoRepeat:1;
        unsigned int applicationKeypad:1;
        unsigned int applicationCursor:1;
        unsigned int localEcho:1;
        unsigned int insertMode:1;
        unsigned int allowDECCOLM:1;
    } _modeFlags;
    CDAnonymousStruct4 _currentAttributes;
    struct {
        unsigned char original;
        char *translated;
        unsigned int length;
        unsigned int custom:1;
    } _baseTranslationTable[128];
    char *_baseTranslationString;
    CDAnonymousStruct1 *_translationTable[5][128];
    unsigned int _currentCharSet;
    unsigned int _savedCharSet;
    unsigned int _selectedCharSet;
    unsigned int _shiftCharSet;
    BOOL _percentCharSet;
    BOOL _defaultTabStops;
    NSMutableIndexSet *_tabStops;
    BOOL _lastPrintedCharacter;
}

- (id)initWithShell:(id)fp8 logicalScreen:(id)fp12 profile:(id)fp16;
- (id)initWithController:(id)fp8;
- (void)dealloc;
- (id)profile;
- (void)setProfile:(id)fp8;
- (void)setObserversForLogicalScreen:(BOOL)fp8;
- (void)vt52EmulationMode:(BOOL)fp8;
- (void)softReset;
- (void)hardReset;
- (id)decodeData:(id)fp8;
- (id)encodeEvent:(id)fp8;
- (unsigned int)cursorRow;
- (unsigned int)unshiftedCursorRow;
- (void)advanceCursorRow;
- (void)setCursorRow:(unsigned int)fp8;
- (unsigned int)rowCount;
- (unsigned int)cursorColumn;
- (void)setCursorColumn:(unsigned int)fp8;
- (void)setColumnCount:(unsigned int)fp8;
- (void)setScrollRange:(struct _NSRange)fp8;
- (void)loadTranslationVector:(CDAnonymousStruct7 *)fp8 intoSet:(unsigned int)fp12;
- (void)resetTabStops;
- (void)performOperatingSystemCommand;
- (void)observeValueForKeyPath:(id)fp8 ofObject:(id)fp12 change:(id)fp16 context:(void *)fp20;

@end

@interface TTLogicalScreen (VT100Additions)
- (void)eraseUTF8Characters:(unsigned int)fp8 withAttributes:(CDAnonymousStruct4)fp12 atPosition:(CDAnonymousStruct5)fp24;
@end

@interface TTTextStorageManager : NSObject
{
    TTLogicalScreen *_screen;
    struct storage_list *_freeListHead;
    struct storage_list *_freeListTail;
    unsigned int _freeListCount;
    CDAnonymousStruct2 *_storageList;
    unsigned int _cursorIndex;
    unsigned int _cursorOffsetIndex;
    unsigned int _characterCount;
    unsigned int _lineCount;
    unsigned int _columnCount;
    NSMutableIndexSet *_doubleHighTopLines;
    NSMutableIndexSet *_doubleHighBottomLines;
    NSMutableIndexSet *_doubleWideLines;
    NSThread *_rewrappingThread;
}

- (id)initWithLogicalScreen:(id)fp8;
- (void)dealloc;
- (id)description;
- (unsigned int)lineCount;
- (unsigned int)columnCount;
- (void)setColumnCount:(unsigned int)fp8;
- (void)rewrappingThread:(id)fp8;
- (void)applyChangesFromRewrappingThread:(id)fp8;
- (void)wrapLinesFromEnd:(unsigned int)fp8 toColumnCount:(unsigned int)fp12;
- (BOOL)initializeFreeList;
- (BOOL)growFreeList:(unsigned int)fp8;
- (BOOL)growFreeList;
- (void)shrinkFreeList;
- (void)deleteFreeList;
- (BOOL)createBuffer;
- (void)releaseStorageListTail;
- (void)releaseStorageListHead;
- (BOOL)initializeStorageList;
- (void)deleteStorageList;
- (void)getLine:(unsigned int)fp8 UTF8Characters:(CDAnonymousStruct2 *)fp12 runs:(CDAnonymousStruct2 *)fp16;
- (void)appendUTF8Characters:(const char *)fp8 length:(unsigned int)fp12 withAttributes:(CDAnonymousStruct4)fp16 doesBeginLine:(BOOL)fp28;
- (void)clearStorageList;
- (void)truncateToCharacterLength:(unsigned int)fp8;
- (void)truncateToLineLength:(unsigned int)fp8;
- (void)truncateToExactLineLength:(unsigned int)fp8;
- (void)truncateFromBeginningToExactLineLength:(unsigned int)fp8;
- (unsigned int)sizeForLine:(unsigned int)fp8;
- (void)setSize:(unsigned int)fp8 forLine:(unsigned int)fp12;
- (void)rewindCursor;
- (void)truncateLineSizes;
- (void)truncateLineSizesFromBeginningFrom:(unsigned int)fp8 to:(unsigned int)fp12;

@end

@interface NSCursor (Terminal)
+ (id)shadowedIBeamCursor;
@end

@interface TTKeyMappingsController : NSObject
{
    NSArrayController *_profilesController;
    NSArrayController *_keyMapController;
    NSTableView *_tableView;
    NSWindow *_keyMappingSheet;
    NSPopUpButton *_keyPopUpButton;
    NSPopUpButton *_modifierPopUpButton;
    NSPopUpButton *_actionPopUpButton;
    NSTextField *_actionTextField;
    NSButton *_addButton;
    NSButton *_deleteButton;
    NSButton *_editButton;
    TTKeyMapTextEscaper *_escaper;
    NSArray *_keys;
    NSArray *_modifiers;
    NSArray *_actions;
}

- (void)dealloc;
- (void)awakeFromNib;
- (void)delete:(id)fp8;
- (void)add:(id)fp8;
- (void)sheetDidEnd:(id)fp8 returnCode:(int)fp12 contextInfo:(void *)fp16;
- (void)edit:(id)fp8;
- (void)cancelSheet:(id)fp8;
- (void)okSheet:(id)fp8;
- (void)actionPopupChanged:(id)fp8;
- (void)tableViewSelectionDidChange:(id)fp8;

@end

@interface TTKeyMapTextEscaper : NSObject
{
    unsigned short *_buf;
    int _buflen;
}

- (void)dealloc;
- (id)escapeString:(id)fp8;
- (id)unescapeString:(id)fp8;

@end

@interface RawTextView : NSTextView
{
    BOOL inPaste;
    BOOL skipShouldChange;
}

- (id)initWithFrame:(struct _NSRect)fp8;
- (void)dealloc;
- (void)delete:(id)fp8;
- (void)deleteBackward:(id)fp8;
- (void)paste:(id)fp8;
- (BOOL)shouldChangeTextInRange:(struct _NSRange)fp8 replacementString:(id)fp16;
- (void)keyDown:(id)fp8;
- (void)moveLeft:(id)fp8;
- (void)moveRight:(id)fp8;
- (struct _NSRange)selectionRangeForProposedRange:(struct _NSRange)fp8 granularity:(unsigned int)fp16;

@end

@interface RawTextField : NSTextField
{
}

@end

@interface RawTextPanel : NSPanel
{
    RawTextView *_rawTextView;
}

- (void)dealloc;
- (id)fieldEditor:(BOOL)fp8 forObject:(id)fp12;

@end

@interface TTAccessibleView : NSView
{
}

- (BOOL)accessibilityIsIgnored;
- (id)accessibilityAttributeValue:(id)fp8;
- (id)accessibilityAttributeValue:(id)fp8 forParameter:(id)fp12;
- (BOOL)accessibilityIsAttributeSettable:(id)fp8;
- (void)accessibilitySetValue:(id)fp8 forAttribute:(id)fp12;

@end

@interface TTNoWarnProcessesController : TTEditingArrayController
{
}

- (id)newObject;

@end

@interface TTWorkspaceArrayController : NSArrayController
{
    NSTableView *_tableView;
}

- (void)awakeFromNib;
- (void)willChangeValuesForArrangedKeys:(BOOL)fp8 objectKeys:(BOOL)fp12 indexKeys:(BOOL)fp16;
- (void)didChangeValuesForArrangedKeys:(BOOL)fp8 objectKeys:(BOOL)fp12 indexKeys:(BOOL)fp16;
- (BOOL)canExport;
- (void)export:(id)fp8;
- (void)exportPanelDidEnd:(id)fp8 returnCode:(int)fp12 contextInfo:(void *)fp16;
- (void)import:(id)fp8;
- (void)importPanelDidEnd:(id)fp8 returnCode:(int)fp12 contextInfo:(void *)fp16;
- (BOOL)panel:(id)fp8 shouldShowFilename:(id)fp12;
- (BOOL)tableView:(id)fp8 writeRowsWithIndexes:(id)fp12 toPasteboard:(id)fp16;
- (id)tableView:(id)fp8 namesOfPromisedFilesDroppedAtDestination:(id)fp12 forDraggedRowsWithIndexes:(id)fp16;
- (unsigned int)tableView:(id)fp8 validateDrop:(id)fp12 proposedRow:(int)fp16 proposedDropOperation:(unsigned int)fp20;
- (BOOL)tableView:(id)fp8 acceptDrop:(id)fp12 row:(int)fp16 dropOperation:(unsigned int)fp20;

@end

@interface TTProfileArrayController : TTEditingArrayController
{
    NSTextField *_commandField;
}

- (void)awakeFromNib;
- (id)newObject;
- (void)willAddObject:(id)fp8;
- (void)willChangeValuesForArrangedKeys:(BOOL)fp8 objectKeys:(BOOL)fp12 indexKeys:(BOOL)fp16;
- (void)didChangeValuesForArrangedKeys:(BOOL)fp8 objectKeys:(BOOL)fp12 indexKeys:(BOOL)fp16;
- (BOOL)canRemove;
- (BOOL)canMakeDefault;
- (void)makeDefault:(id)fp8;
- (void)duplicate:(id)fp8;
- (void)restoreDefaults:(id)fp8;
- (BOOL)canExport;
- (void)export:(id)fp8;
- (void)exportPanelDidEnd:(id)fp8 returnCode:(int)fp12 contextInfo:(void *)fp16;
- (void)import:(id)fp8;
- (void)importPanelDidEnd:(id)fp8 returnCode:(int)fp12 contextInfo:(void *)fp16;
- (BOOL)panel:(id)fp8 shouldShowFilename:(id)fp12;
- (id)shouldRunCommandAtStartup;
- (void)setShouldRunCommandAtStartup:(id)fp8;
- (BOOL)tableView:(id)fp8 writeRowsWithIndexes:(id)fp12 toPasteboard:(id)fp16;
- (id)tableView:(id)fp8 namesOfPromisedFilesDroppedAtDestination:(id)fp12 forDraggedRowsWithIndexes:(id)fp16;
- (unsigned int)tableView:(id)fp8 validateDrop:(id)fp12 proposedRow:(int)fp16 proposedDropOperation:(unsigned int)fp20;
- (BOOL)tableView:(id)fp8 acceptDrop:(id)fp12 row:(int)fp16 dropOperation:(unsigned int)fp20;

@end

@interface TTEditingArrayController : NSArrayController
{
    NSTableView *_tableView;
}

- (void)add:(id)fp8;

@end

@interface TTAppPrefsController : NSWindowController
{
    NSMatrix *_defaultShellMatrix;
    NSTextField *_defaultShellTextField;
    NSTabView *_tabView;
    NSArrayController *_profilesController;
    NSArrayController *_workspacesController;
    NSTableView *_profilesTableView;
    NSMenuItem *_profilesActionMenuItem;
    TTTableView *_workspacesTableView;
    NSMenuItem *_workspacesActionMenuItem;
    NSView *_fontAccessoryView;
    BOOL _wasFontPanelVisible;
    BOOL _wasColorPanelVisible;
    NSUndoManager *_undoManager;
    TTView *_thumbnailView;
    TTLogicalScreen *_thumbnailScreen;
}

+ (id)sharedPreferencesController;
- (id)init;
- (void)dealloc;
- (void)applicationWillTerminate:(id)fp8;
- (void)windowDidLoad;
- (id)windowWillReturnUndoManager:(id)fp8;
- (id)undoManager;
- (void)showWindow:(id)fp8;
- (void)windowDidResignKey:(id)fp8;
- (void)windowWillClose:(id)fp8;
- (void)update;
- (void)defaultShellChanged:(id)fp8;
- (void)showEncodingCustomizationPane:(id)fp8;
- (void)orderFrontFontPanel:(id)fp8;
- (id)profilesController;
- (id)selectedPaneIdentifier;
- (void)setSelectedPaneIdentifier:(id)fp8;
- (void)tabView:(id)fp8 willSelectTabViewItem:(id)fp12;
- (void)tabView:(id)fp8 didSelectTabViewItem:(id)fp12;
- (void)takeSelectedTabIndexFromToolbarItem:(id)fp8;
- (id)toolbar:(id)fp8 itemForItemIdentifier:(id)fp12 willBeInsertedIntoToolbar:(BOOL)fp16;
- (id)toolbarDefaultItemIdentifiers:(id)fp8;
- (id)toolbarAllowedItemIdentifiers:(id)fp8;
- (id)toolbarSelectableItemIdentifiers:(id)fp8;
- (id)thumbnailView;
- (id)thumbnailOfSize:(struct _NSSize)fp8 forProfile:(id)fp16;
- (void)changeFont:(id)fp8;
- (void)observeValueForKeyPath:(id)fp8 ofObject:(id)fp12 change:(id)fp16 context:(void *)fp20;

@end

@interface TTLogicalScreen (SampleText)
- (void)insertSampleText;
@end

@interface TTProfileManager (UndoCompatibleKeyValueCoding)
- (void)undoCompatibleSetValue:(id)fp8 forKeyPath:(id)fp12;
- (void)undoCompatibleInsertObjects:(id)fp8 intoKeyPath:(id)fp12;
- (void)undoCompatibleRemoveObjects:(id)fp8 fromKeyPath:(id)fp12;
- (void)undoCompatibleReplaceObjects:(id)fp8 withObjects:(id)fp12 atKeyPath:(id)fp16;
@end

@interface TTProfile (UndoCompatibleKeyValueCoding)
- (void)undoCompatibleSetValue:(id)fp8 forKeyPath:(id)fp12;
@end

@interface TTApplication : NSApplication
{
    NSMutableIndexSet *_availableEquivalents;
    NSMutableDictionary *_windowEquivalents;
    NSMenu *_equivalentsMenu;
    NSMutableArray *_windowsToPromptForCloseArray;
    BOOL _isTerminating;
    BOOL _illegalShell;
    NSString *_defaultShell;
    NSString *_termType;
    TTWorkspace *_currentWorkspace;
    TTWindow *_mainTerminalWindow;
    TTWindowController *_mainTerminalWindowController;
    NSMenuItem *_closeWindowMenuItem;
    NSMenuItem *_closeAllMenuItem;
    NSMenuItem *_closeTabMenuItem;
    NSMenuItem *_closeOtherTabsMenuItem;
    NSMenuItem *_servicesMenuItem;
    NSMenuItem *_helpMenuItem;
    NSMenu *_newWindowMenu;
    NSMenu *_newTabMenu;
    NSMenu *_newWindowDockMenu;
    NSMenu *_dockMenu;
}

+ (void)initialize;
+ (struct __CFURL *)alertSoundURL;
+ (BOOL)isRunningInInstallEnvironment;
- (id)init;
- (void)dealloc;
- (void)setDefaultShell:(id)fp8;
- (id)defaultShell;
- (BOOL)authorizeShell;
- (void)awakeFromNib;
- (void)setDockMenu:(id)fp8;
- (void)finishLaunching;
- (void)applicationDidFinishLaunching:(id)fp8;
- (void)migrateDefaults;
- (id)importDefaultSettingsOverwritingExisting:(BOOL)fp8;
- (void)newShell:(id)fp8;
- (void)newTab:(id)fp8;
- (void)newShell:(id)fp8 withProfile:(id)fp12;
- (id)newWindowControllerWithProfile:(id)fp8;
- (id)newWindowControllerWithProfile:(id)fp8 command:(id)fp12 runAsShell:(BOOL)fp16;
- (BOOL)applicationShouldHandleReopen:(id)fp8 hasVisibleWindows:(BOOL)fp12;
- (void)showPreferencesWindow:(id)fp8;
- (void)sneakilyOrderFrontFontPanel:(id)fp8;
- (void)toggleProfileInspector:(id)fp8;
- (void)toggleInspectorPanel:(id)fp8;
- (void)open:(id)fp8;
- (BOOL)application:(id)fp8 openTempFile:(id)fp12;
- (void)connectToServer:(id)fp8;
- (BOOL)application:(id)fp8 openFile:(id)fp12;
- (unsigned int)applicationShouldTerminate:(id)fp8;
- (void)continueTermination:(id)fp8;
- (void)cancelTermination:(id)fp8;
- (void)didPresentErrorWithRecovery:(BOOL)fp8 contextInfo:(void *)fp12;
- (BOOL)openFile:(id)fp8;
- (void)newCommand:(id)fp8;
- (BOOL)openCommandFile:(id)fp8;
- (BOOL)openTermFile:(id)fp8;
- (id)importTermFile:(id)fp8;
- (BOOL)openSettingsFile:(id)fp8;
- (BOOL)importSettingsFiles:(id)fp8 overwritingExisting:(BOOL)fp12 profiles:(id *)fp16 workspaces:(id *)fp20 error:(id *)fp24;
- (void)applyProfileToAllWindowControllers:(id)fp8;
- (void)handleWindowKeyChange:(id)fp8;
- (void)applicationDidBecomeActive:(id)fp8;
- (void)applicationDidResignActive:(id)fp8;
- (void)addWindowController:(id)fp8;
- (void)addWindowController:(id)fp8 withProfileID:(int)fp12;
- (id)currentWorkspace;
- (void)saveWorkspace:(id)fp8;
- (void)openWorkspace:(id)fp8;
- (void)openWorkspaceRepresentation:(id)fp8;
- (id)mainTerminalWindow;
- (void)observeValueForKeyPath:(id)fp8 ofObject:(id)fp12 change:(id)fp16 context:(void *)fp20;
- (void)setSecureKeyboardEntryFromDefaults;
- (void)setSecureKeyboardEntry:(BOOL)fp8;
- (void)toggleSecureKeyboardEntry:(id)fp8;
- (void)showHelpAnchorWithTag:(id)fp8;
- (BOOL)validateMenuItem:(id)fp8;
- (void)updateShellMenu;
- (void)updateWindowMenu;
- (void)addWindowsItem:(id)fp8 title:(id)fp12 filename:(BOOL)fp16;
- (void)changeWindowsItem:(id)fp8 title:(id)fp12 filename:(BOOL)fp16;
- (void)updateWindowsItem:(id)fp8;
- (void)removeWindowsItem:(id)fp8;
- (void)menuNeedsUpdate:(id)fp8;
- (void)profileMenuNeedsUpdate:(id)fp8;
- (void)workspaceMenuNeedsUpdate:(id)fp8;
- (unsigned int)registerProfileID:(id)fp8;
- (void)releaseProfileID:(unsigned int)fp8;
- (id)keyEquivalentForProfileID:(unsigned int)fp8;
- (unsigned int)keyEquivalentModifierMaskForProfileID:(unsigned int)fp8;
- (void)sendEvent:(id)fp8;
- (void)orderFrontStandardAboutPanel:(id)fp8;

@end

@interface TTStartupActionIsUseWindowGroupTransformer : NSValueTransformer
{
}

+ (Class)transformedValueClass;
+ (BOOL)allowsReverseTransformation;
- (id)transformedValue:(id)fp8;

@end

@interface TTStartupActionIsUseWindowSettingsTransformer : NSValueTransformer
{
}

+ (Class)transformedValueClass;
+ (BOOL)allowsReverseTransformation;
- (id)transformedValue:(id)fp8;

@end

@interface TTView (TTAccessibility)
+ (struct _NSRect)convertScreenToAccessibility:(struct _NSRect)fp8;
- (id)accessibilityAttributeNames;
- (id)accessibilityParameterizedAttributeNames;
- (id)ttaxRoleAttribute;
- (BOOL)ttaxIsRoleAttributeMutable;
- (id)ttaxDescriptionAttribute;
- (BOOL)ttaxIsDescriptionAttributeMutable;
- (id)ttaxSizeAttribute;
- (BOOL)ttaxIsSizeAttributeMutable;
- (id)ttaxPositionAttribute;
- (BOOL)ttaxIsPositionAttributeMutable;
- (id)ttaxValueAttribute;
- (BOOL)ttaxIsValueAttributeMutable;
- (id)ttaxNumberOfCharactersAttribute;
- (BOOL)ttaxIsNumberOfCharactersAttributeMutable;
- (id)ttaxSelectedTextAttribute;
- (BOOL)ttaxIsSelectedTextAttributeMutable;
- (id)ttaxSelectedTextRangeAttribute;
- (void)ttaxSetSelectedTextRangeAttribute:(id)fp8;
- (BOOL)ttaxIsSelectedTextRangeAttributeMutable;
- (id)ttaxSelectedTextRangesAttribute;
- (void)ttaxSetSelectedTextRangesAttribute:(id)fp8;
- (BOOL)ttaxIsSelectedTextRangesAttributeMutable;
- (id)ttaxInsertionPointLineNumberAttribute;
- (BOOL)ttaxIsInsertionPointLineNumberAttributeMutable;
- (id)ttaxVisibleCharacterRangeAttribute;
- (BOOL)ttaxIsVisibleCharacterRangeAttributeMutable;
- (id)ttaxLineForIndexAttributeForParameter:(id)fp8;
- (id)ttaxRangeForLineAttributeForParameter:(id)fp8;
- (id)ttaxStringForRangeAttributeForParameter:(id)fp8;
- (id)ttaxRangeForPositionAttributeForParameter:(id)fp8;
- (id)ttaxRangeForIndexAttributeForParameter:(id)fp8;
- (id)ttaxBoundsForRangeAttributeForParameter:(id)fp8;
- (void)ttaxEmulatorDidDecodeData:(id)fp8;
- (void)notifyAccessiblityAboutCursorLocation;
@end

@interface TTLogicalScreenString : NSString
{
    TTLogicalScreen *_screen;
    CDAnonymousStruct2 *_UTF8Buffer;
    CDAnonymousStruct2 *_UTF16Buffer;
    CDAnonymousStruct2 *_runBuffer;
    struct _NSRange _backingStoreRange;
    unsigned int _generation;
}

+ (id)stringWithLogicalScreen:(id)fp8;
- (id)initWithLogicalScreen:(id)fp8;
- (void)dealloc;
- (unsigned int)length;
- (unsigned short)characterAtIndex:(unsigned int)fp8;
- (void)getCharacters:(unsigned short *)fp8 range:(struct _NSRange)fp12;

@end

@interface TTLogicalScreen (UnicharAccessInternal)
- (void)initUnicharAccess;
- (void)deallocUnicharAccess;
- (unsigned int)unicharOffsetCacheGenerationNumber;
- (void)truncateUnicharOffsetCacheAtLine:(unsigned int)fp8;
- (void)expandUnicharOffsetCacheToLine:(unsigned int)fp8;
- (unsigned int)unicharOffsetForLine:(unsigned int)fp8;
- (void)convertSpacesToTabs:(CDAnonymousStruct2 *)fp8 withRuns:(CDAnonymousStruct2 *)fp12;
- (unsigned int)reverseUnicharOffsetForDisplayPosition:(CDAnonymousStruct5)fp8;
- (CDAnonymousStruct5)displayPositionForReverseUnicharOffset:(unsigned int)fp8;
@end

@interface TTLogicalScreen (UnicharAccess)
- (id)string;
- (unsigned int)unicharLength;
- (unsigned int)unicharOffsetForDisplayPosition:(CDAnonymousStruct5)fp8;
- (CDAnonymousStruct5)displayPositionForUnicharOffset:(unsigned int)fp8;
- (struct _NSRange)unicharRangeForLine:(unsigned int)fp8;
- (id)stringForUnicharRange:(struct _NSRange)fp8;
@end

@interface TTWindow (Scripting)
- (id)tabControllers;
- (id)selectedTabController;
- (void)setSelectedTabController:(id)fp8;
- (BOOL)scriptFrontmost;
- (void)setScriptFrontmost:(BOOL)fp8;
- (id)scriptPosition;
- (void)setScriptPosition:(id)fp8;
- (id)scriptOrigin;
- (void)setScriptOrigin:(id)fp8;
- (id)scriptSize;
- (void)setScriptSize:(id)fp8;
- (id)scriptFrame;
- (void)setScriptFrame:(id)fp8;
- (void)setBoundsAsQDRect:(id)fp8;
- (id)handleDoScriptCommand:(id)fp8;
@end

@interface TTTabController (Scripting)
- (id)objectSpecifier;
- (void)prepareScriptingProfile;
- (unsigned int)scriptNumberOfRows;
- (void)setScriptNumberOfRows:(unsigned int)fp8;
- (unsigned int)scriptNumberOfColumns;
- (void)setScriptNumberOfColumns:(unsigned int)fp8;
- (id)scriptCursorColor;
- (void)setScriptCursorColor:(id)fp8;
- (id)scriptBackgroundColor;
- (void)setScriptBackgroundColor:(id)fp8;
- (id)scriptNormalTextColor;
- (void)setScriptNormalTextColor:(id)fp8;
- (id)scriptBoldTextColor;
- (void)setScriptBoldTextColor:(id)fp8;
- (id)scriptContents;
- (id)scriptHistory;
- (BOOL)scriptBusy;
- (id)scriptProcesses;
- (BOOL)scriptSelected;
- (void)setScriptSelected:(BOOL)fp8;
- (id)scriptCleanCommands;
- (void)setScriptCleanCommands:(id)fp8;
- (BOOL)scriptTitleDisplaysDeviceName;
- (void)setScriptTitleDisplaysDeviceName:(BOOL)fp8;
- (BOOL)scriptTitleDisplaysShellPath;
- (void)setScriptTitleDisplaysShellPath:(BOOL)fp8;
- (BOOL)scriptTitleDisplaysWindowSize;
- (void)setScriptTitleDisplaysWindowSize:(BOOL)fp8;
- (BOOL)scriptTitleDisplaysFileName;
- (void)setScriptTitleDisplaysFileName:(BOOL)fp8;
- (BOOL)scriptTitleDisplaysCustomTitle;
- (void)setScriptTitleDisplaysCustomTitle:(BOOL)fp8;
- (id)scriptCustomTitle;
- (void)setScriptCustomTitle:(id)fp8;
- (id)scriptTTY;
- (id)scriptFontName;
- (void)setScriptFontName:(id)fp8;
- (int)scriptFontSize;
- (void)setScriptFontSize:(int)fp8;
- (BOOL)scriptFontAntialiasing;
- (void)setScriptFontAntialiasing:(BOOL)fp8;
- (id)handleDoScriptCommand:(id)fp8;
@end

@interface TTApplication (Scripting)
- (id)handleDoScriptCommand:(id)fp8;
- (void)handleGetURLScriptCommand:(id)fp8;
- (id)scriptSettings;
- (void)setScriptSettings:(id)fp8;
- (void)insertInScriptSettings:(id)fp8;
- (id)scriptDefaultSettings;
- (void)setScriptDefaultSettings:(id)fp8;
- (id)scriptStartupSettings;
- (void)setScriptStartupSettings:(id)fp8;
@end

@interface TTDoScriptCommand : NSScriptCommand
{
}

- (id)performDefaultImplementation;

@end

@interface NSAppleEventDescriptor (Terminal)
- (BOOL)isNullDescriptor;
@end

@interface TTEncodingController : NSObject
{
    NSArray *_availableEncodings;
    NSArray *_enabledEncodings;
    unsigned int _transientEncoding;
}

+ (void)initialize;
+ (id)defaultEncodings;
+ (id)sharedEncodingController;
- (id)init;
- (void)dealloc;
- (void)setTransientEncoding:(unsigned int)fp8;
- (id)availableEncodings;
- (id)enabledEncodings;
- (void)enableAll:(id)fp8;
- (void)disableAll:(id)fp8;
- (void)revertToDefaults:(id)fp8;
- (void)enabledEncodingsDidChange;
- (id)enabledEncodingsArray;

@end

@interface TTEncodingBindingEntry : NSObject
{
    unsigned int _encoding;
}

+ (id)bindingEntryWithEncoding:(unsigned int)fp8;
- (id)initWithEncoding:(unsigned int)fp8;
- (void)dealloc;
- (id)localizedName;
- (unsigned int)encoding;
- (BOOL)isEnabled;
- (void)setEnabled:(BOOL)fp8;
- (void)observeValueForKeyPath:(id)fp8 ofObject:(id)fp12 change:(id)fp16 context:(void *)fp20;

@end

@interface NSArray (Terminal)
- (id)sortedArrayUsingEncodingSort;
@end

@interface NSNumber (Terminal)
- (int)compareAsNSStringEncoding:(id)fp8;
- (int)compareAsNSStringEncodingByUnicode:(id)fp8;
- (int)compareAsNSStringEncodingByMacStringEncoding:(id)fp8;
- (int)compareAsNSStringEncodingByCFStringEncoding:(id)fp8;
@end

@interface TTClipView : NSClipView
{
    float _documentHeight;
    struct _NSPoint _lastScrollPoint;
}

- (void)setDocumentView:(id)fp8;
- (void)viewFrameChanged:(id)fp8;
- (void)scrollToPoint:(struct _NSPoint)fp8;

@end

@interface TTProfileManager : NSObject
{
    NSMutableArray *_profiles;
    TTProfile *_defaultProfile;
    TTProfile *_startupProfile;
    BOOL _isLoadingFromDefaults;
}

+ (id)sharedProfileManager;
- (id)init;
- (void)dealloc;
- (void)synchronize;
- (id)profiles;
- (void)setProfiles:(id)fp8;
- (unsigned int)countOfProfiles;
- (void)insertObject:(id)fp8 inProfilesAtIndex:(unsigned int)fp12;
- (void)removeObjectFromProfilesAtIndex:(unsigned int)fp8;
- (void)replaceObjectInProfilesAtIndex:(unsigned int)fp8 withObject:(id)fp12;
- (id)profileWithName:(id)fp8;
- (void)setProfile:(id)fp8 forName:(id)fp12;
- (id)uniqueProfileNameWithBase:(id)fp8;
- (id)defaultProfile;
- (void)setDefaultProfile:(id)fp8;
- (id)startupProfile;
- (void)setStartupProfile:(id)fp8;
- (id)profileSavePanel;

@end

@interface TTProfileManager (Internal)
- (void)saveToDefaults:(id)fp8;
- (void)loadFromDefaults:(id)fp8;
- (void)observeValueForKeyPath:(id)fp8 ofObject:(id)fp12 change:(id)fp16 context:(void *)fp20;
@end

@interface TTGenericSavePanel : NSWindowController
{
    NSString *_name;
    NSString *_objectName;
    BOOL _isObjectNameCountable;
    NSString *_title;
    NSArray *_representedObjects;
    NSViewController *_accessoryController;
    BOOL _isDisplayingSheet;
    id _modalForWindow;
    id _modalDelegate;
    SEL _didEndSelector;
    NSComboBoxCell *_nameField;
    NSButton *_saveButton;
    NSButton *_cancelButton;
    NSBox *_accessoryBox;
    NSBox *_lineBox;
}

+ (id)savePanel;
- (id)init;
- (void)dealloc;
- (void)setName:(id)fp8;
- (id)name;
- (void)setObjectName:(id)fp8;
- (id)objectName;
- (void)setObjectNameCountable:(BOOL)fp8;
- (BOOL)isObjectNameCountable;
- (id)title;
- (void)setTitle:(id)fp8;
- (void)setRepresentedObjects:(id)fp8;
- (id)representedObjects;
- (void)setAccessoryController:(id)fp8;
- (id)accessoryController;
- (void)beginSheetModalForWindow:(id)fp8 modalDelegate:(id)fp12 didEndSelector:(SEL)fp16;
- (int)runModal;
- (void)sheetDidEnd:(id)fp8 returnCode:(int)fp12 contextInfo:(void *)fp16;
- (void)sheetDidEndWithReturnCode:(int)fp8;
- (id)windowNibName;
- (void)save:(id)fp8;
- (void)didPresentErrorWithRecovery:(BOOL)fp8 contextInfo:(void *)fp12;
- (void)alertDidEnd:(id)fp8 returnCode:(int)fp12 contextInfo:(void *)fp16;
- (void)cancel:(id)fp8;
- (void)endWithReturnCode:(int)fp8;
- (void)preparePanel;
- (void)handleComboBoxChange:(id)fp8;
- (void)controlTextDidChange:(id)fp8;

@end

@interface TTGenericPickerPanel : NSWindowController
{
    id _representedObject;
    id _defaultRepresentedObject;
    NSArray *_representedObjects;
    NSString *_title;
    NSString *_prompt;
    NSString *_message;
    id _modalDelegate;
    SEL _didEndSelector;
    NSButton *_defaultButton;
    NSTextField *_messageField;
}

+ (id)pickerPanel;
- (id)init;
- (void)dealloc;
- (id)representedObjects;
- (void)setRepresentedObjects:(id)fp8;
- (id)title;
- (void)setTitle:(id)fp8;
- (id)prompt;
- (void)setPrompt:(id)fp8;
- (id)message;
- (void)setMessage:(id)fp8;
- (id)representedObject;
- (void)setRepresentedObject:(id)fp8;
- (id)defaultRepresentedObject;
- (void)setDefaultRepresentedObject:(id)fp8;
- (void)beginSheetModalForWindow:(id)fp8 modalDelegate:(id)fp12 didEndSelector:(SEL)fp16;
- (int)runModal;
- (void)open:(id)fp8;
- (void)cancel:(id)fp8;
- (id)windowNibName;
- (void)endWithReturnCode:(int)fp8;
- (void)sheetDidEnd:(id)fp8 returnCode:(int)fp12 contextInfo:(void *)fp16;
- (void)preparePanel;
- (void)prepareRepresentedObject;

@end

@interface TTFindPanel : NSPanel
{
    NSComboBox *_findPatternField;
    NSButton *_findNextButton;
    NSButton *_findPreviousButton;
    NSButton *_ignoreCaseCheckbox;
    NSButton *_wrapAroundCheckbox;
    NSTextField *_notFoundLabel;
    BOOL _isFindPatternDirty;
}

+ (id)sharedFindPanel;
- (id)initWithContentRect:(struct _NSRect)fp8 styleMask:(unsigned int)fp24 backing:(unsigned int)fp28 defer:(BOOL)fp32;
- (void)dealloc;
- (id)findPattern;
- (unsigned int)stringCompareOptions;
- (void)performTerminalFindPanelAction:(id)fp8;
- (void)findNext:(id)fp8;
- (void)findPrevious:(id)fp8;
- (void)becomeKeyWindow;
- (BOOL)validateMenuItem:(id)fp8;
- (void)controlTextDidChange:(id)fp8;
- (void)comboBoxSelectionDidChange:(id)fp8;
- (void)applicationDidBecomeActive:(id)fp8;
- (void)initContentView;
- (void)pushChangesToPasteboard;
- (void)pullChangesFromPasteboard;
- (void)updateRecentPatterns;
- (id)target;
- (BOOL)conformsToFindingProtocol:(id)fp8;
- (void)performFindWithOptions:(unsigned int)fp8;

@end

@interface TTIOManager : NSObject
{
    NSLock *_readLock;
    NSLock *_writeLock;
    NSLock *_deadLock;
    NSLock *_signalLock;
    int _signalPipe[2];
    NSMutableDictionary *_readQueue;
    NSMutableDictionary *_writeQueue;
    NSMutableDictionary *_shells;
    NSMutableDictionary *_deadShells;
    struct fd_set _readDescriptors;
    struct fd_set _writeDescriptors;
    BOOL _didRunMainThread;
}

+ (id)sharedIOManager;
- (id)init;
- (void)dealloc;
- (void)addShell:(id)fp8;
- (void)removeShell:(id)fp8;
- (void)signalShell:(id)fp8;
- (void)writeData:(id)fp8 forShell:(id)fp12;
- (void)signalIOThread;
- (void)IOThread;
- (void)mainThread;

@end

@interface TTRunCommandPanelController : NSWindowController
{
    NSComboBox *_commandCombo;
    NSButton *_runInShellCheckBox;
}

+ (id)sharedRunCommandPanel;
- (id)initWithWindowNibName:(id)fp8;
- (void)windowDidLoad;
- (void)showWindow:(id)fp8;
- (void)dealloc;
- (void)commandEntered:(id)fp8;

@end

@interface ServiceBrowser : NSObject
{
    NSButtonCell *_addService;
    NSButtonCell *_removeService;
    NSButtonCell *_addServer;
    NSButtonCell *_removeServer;
    NSPopUpButton *_options;
    NSComboBox *_connectCommandLine;
    NSTextField *_usernameText;
    NSButton *_connectButton;
    NSBrowser *_serviceBrowser;
    NSWindow *_window;
    NSMutableArray *_servicesToWatch;
    NSArray *_discoveredServers;
    NSMutableArray *_updatedDiscoveredServers;
    NSMutableArray *_permanentServers;
    NSMutableDictionary *_refCountedReferences;
    NSNetServiceBrowser *_currentBrowser;
    NSNetService *_currentResolve;
    NSWindow *_addServerSheet;
    NSTextField *_newServerAddress;
    NSWindow *_addServiceSheet;
    NSTextField *_newServiceType;
    NSTextField *_newServiceName;
    NSTextField *_newServiceCommand;
    NSButton *_newServiceUsesUser;
}

+ (id)serviceBrowser;
- (id)init;
- (void)dealloc;
- (void)connect:(id)fp8;
- (void)addService:(id)fp8;
- (void)removeService:(id)fp8;
- (void)serverSheetDidEnd:(id)fp8 returnCode:(int)fp12 contextInfo:(void *)fp16;
- (void)serviceSheetDidEnd:(id)fp8 returnCode:(int)fp12 contextInfo:(void *)fp16;
- (void)sheetAddServer:(id)fp8;
- (void)sheetCancelAddServer:(id)fp8;
- (void)sheetAddService:(id)fp8;
- (void)sheetCancelAddService:(id)fp8;
- (void)addServer:(id)fp8;
- (void)removeServer:(id)fp8;
- (void)selectionChange:(id)fp8;
- (void)buildCommandLine;
- (void)controlTextDidChange:(id)fp8;
- (void)display;
- (void)addUserDefinedServices;
- (void)writeUserDefinedServices;
- (void)reloadServices;
- (int)_indexOfClosestDiscoveredServer:(id)fp8;
- (int)_indexOfMatchedDiscoveredServer:(id)fp8;
- (void)_updateScrollView;
- (int)browser:(id)fp8 numberOfRowsInColumn:(int)fp12;
- (void)browser:(id)fp8 willDisplayCell:(id)fp12 atRow:(int)fp16 column:(int)fp20;
- (void)netServiceBrowserWillSearch:(id)fp8;
- (void)netServiceBrowser:(id)fp8 didFindService:(id)fp12 moreComing:(BOOL)fp16;
- (void)netServiceBrowser:(id)fp8 didRemoveService:(id)fp12 moreComing:(BOOL)fp16;
- (void)netServiceDidResolveAddress:(id)fp8;
- (void)netService:(id)fp8 didNotResolve:(id)fp12;
- (void)windowWillClose:(id)fp8;

@end

@interface ConnectToService : NSObject
{
    NSString *_userVisibleName;
    NSString *_bonjourName;
    NSDictionary *_commandOptions;
    BOOL _acceptsUsername;
    BOOL _builtIn;
    NSString *_portLocation;
}

+ (id)newWithDictionary:(id)fp8;
- (id)options;
- (id)bonjourName;
- (id)userVisibleName;
- (id)portLocation;
- (BOOL)acceptsUsername;
- (BOOL)builtIn;
- (id)initWithName:(id)fp8 commandOptions:(id)fp12 bonjourName:(id)fp16 usesUser:(BOOL)fp20 portLocation:(id)fp24 builtIn:(BOOL)fp28;
- (void)dealloc;
- (id)dictionaryDescription;

@end

@interface NSNetService (TerminalAdditions)
- (int)compare:(id)fp8;
@end

@interface TTWorkspaceManager : NSObject
{
    NSMutableArray *_workspaces;
    TTWorkspace *_startupWorkspace;
    BOOL _isLoadingFromDefaults;
}

+ (id)sharedWorkspaceManager;
- (id)init;
- (void)dealloc;
- (void)synchronize;
- (id)workspaces;
- (void)setWorkspaces:(id)fp8;
- (unsigned int)countOfWorkspaces;
- (void)insertObject:(id)fp8 inWorkspacesAtIndex:(unsigned int)fp12;
- (void)removeObjectFromWorkspacesAtIndex:(unsigned int)fp8;
- (void)replaceObjectInWorkspacesAtIndex:(unsigned int)fp8 withObject:(id)fp12;
- (id)workspaceWithName:(id)fp8;
- (void)setWorkspace:(id)fp8 forName:(id)fp12;
- (id)uniqueWorkspaceNameWithBase:(id)fp8;
- (id)startupWorkspace;
- (void)setStartupWorkspace:(id)fp8;
- (id)workspaceSavePanel;

@end

@interface TTWorkspaceManager (Internal)
- (void)saveToDefaults:(id)fp8;
- (void)loadFromDefaults:(id)fp8;
@end

@interface TTLogicalScreen (DirtyTrackingInternal)
- (void)initDirtyTracking;
- (void)deallocDirtyTracking;
- (void)markLineAsDirty:(unsigned int)fp8;
- (void)markRowAsDirty:(unsigned int)fp8;
- (void)markLinesInRangeAsDirty:(struct _NSRange)fp8;
@end

@interface TTLogicalScreen (DirtyTracking)
- (id)dirtyLines;
- (void)clearDirtyLines;
@end

@interface NSData (Terminal)
- (id)dataByEscapingEightBitCharacters;
@end

@interface TTView (Selection)
- (void)selectTextBetweenDisplayPositions:(CDAnonymousStruct5)fp8 positionTwo:(CDAnonymousStruct5)fp16 rememberPositions:(BOOL)fp24;
- (void)appendSelectionToDisplayPosition:(CDAnonymousStruct5)fp8 rememberPositions:(BOOL)fp16;
- (void)findWordAtPosition:(CDAnonymousStruct5)fp8 startPosition:(CDAnonymousStruct5 *)fp16 endPosition:(CDAnonymousStruct5 *)fp20;
- (void)findLineAtPosition:(CDAnonymousStruct5)fp8 startPosition:(CDAnonymousStruct5 *)fp16 endPosition:(CDAnonymousStruct5 *)fp20;
- (void)findPathAtPosition:(CDAnonymousStruct5)fp8 startPosition:(CDAnonymousStruct5 *)fp16 endPosition:(CDAnonymousStruct5 *)fp20;
- (BOOL)selectionContainsDisplayPosition:(CDAnonymousStruct5)fp8;
- (void)clipSelectionRanges;
- (void)clearTextSelection;
- (void)setSelectedRange:(struct _NSRange)fp8;
- (void)setSelectedRanges:(id)fp8;
- (BOOL)hasSelection;
- (BOOL)hasActiveSelection;
- (void)selectionFlagsChanged:(id)fp8;
- (void)selectionMouseDown:(id)fp8;
- (void)selectionMouseUp:(id)fp8;
- (void)selectionMouseDragged:(id)fp8;
- (void)selectionOtherMouseDown:(id)fp8;
- (void)dragSelectionWithEvent:(id)fp8;
- (void)draggedImage:(id)fp8 endedAt:(struct _NSPoint)fp12 operation:(unsigned int)fp20;
@end

@interface TTView (SelectionInternal)
+ (double)dragAndDropTextDelay;
- (void)initSelection;
- (void)deallocSelection;
- (struct _NSPoint)pointByRoundingToCellBoundary:(struct _NSPoint)fp8;
- (void)extendSelectionToMatchingCharacter;
- (unsigned short)matchingCharacterForCharacter:(unsigned short)fp8 matchType:(unsigned int *)fp12;
- (void)moveCursorToPosition:(CDAnonymousStruct5)fp8 event:(id)fp16;
@end

@interface NSEvent (TTMenuEvent)
+ (id)eventByChangingKeyEvent:(id)fp8 toCharacters:(id)fp12;
+ (id)eventByChangingKeyEvent:(id)fp8 toCharacters:(id)fp12 withModifierFlags:(unsigned int)fp16;
- (unsigned short)characterCodeWithModifierFlags:(unsigned int)fp8;
- (unsigned short)characterCodeWithCarbonModifiers:(unsigned long)fp8;
- (BOOL)isCommandEqualBelowPlusKeyDown;
- (BOOL)isCommandUnderscoreAboveMinusKeyDown;
- (BOOL)isCommandShiftLeftArrowDown;
- (BOOL)isCommandShiftRightArrowDown;
@end

@interface TTProfileSaveViewController : NSViewController
{
    NSTextField *_commandField;
    NSButton *_useAsDefaultCheckbox;
    NSButton *_useAsStartupCheckbox;
    NSNumber *_savedUseAsDefault;
    NSNumber *_savedUseAsStartup;
}

- (id)shouldRunCommandAtStartup;
- (void)setShouldRunCommandAtStartup:(id)fp8;
- (BOOL)validateName:(id *)fp8 error:(id *)fp12;
- (void)controlTextDidChange:(id)fp8;

@end

@interface TTWorkspaceSaveViewController : NSViewController
{
    NSButton *_useAsStartupCheckbox;
    NSNumber *_savedUseAsStartup;
}

- (void)controlTextDidChange:(id)fp8;

@end

@interface NSAttributedString (Terminal)
- (id)pathAtIndex:(unsigned int)fp8 effectiveRange:(struct _NSRange *)fp12;
@end

@interface NSIndexSet (Terminal)
- (id)subsetWithIndexesInRange:(struct _NSRange)fp8;
@end

@interface TTView (Thumbnail)
- (float)thumbnailScaleFactorForSize:(struct _NSSize)fp8;
- (struct _NSSize)thumbnailSizeForSize:(struct _NSSize)fp8;
- (id)thumbnailImageWithProfile:(id)fp8 size:(struct _NSSize)fp12;
- (id)focusedThumbnailImageWithProfile:(id)fp8 size:(struct _NSSize)fp12;
@end

@interface TTSettingsSourceCell : NSTextFieldCell
{
    NSTextFieldCell *_titleCell;
    NSTextFieldCell *_defaultCell;
    NSImageCell *_thumbnailCell;
    BOOL _isEditing;
    id _dataSource;
}

- (id)initWithCoder:(id)fp8;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (void)dealloc;
- (void)setBackgroundStyle:(int)fp8;
- (struct _NSRect)expansionFrameWithFrame:(struct _NSRect)fp8 inView:(id)fp24;
- (id)profile;
- (BOOL)shouldShowDefaultCell;
- (struct _NSRect)titleRectForBounds:(struct _NSRect)fp8;
- (struct _NSRect)defaultRectForBounds:(struct _NSRect)fp8;
- (void)selectWithFrame:(struct _NSRect)fp8 inView:(id)fp24 editor:(id)fp28 delegate:(id)fp32 start:(int)fp36 length:(int)fp40;
- (void)drawInteriorWithFrame:(struct _NSRect)fp8 inView:(id)fp24;
- (id)thumbnailImage;

@end

@interface TTSettingsThumbnailArrayController : NSArrayController
{
    NSTableView *_tableView;
    NSTimer *_needsDisplayTimer;
    double _lastUpdateTime;
    BOOL _needsDelayedDisplay;
}

- (void)awakeFromNib;
- (void)dealloc;
- (void)observeValueForKeyPath:(id)fp8 ofObject:(id)fp12 change:(id)fp16 context:(void *)fp20;
- (void)setSelectedProfile:(id)fp8;
- (void)showSettingsPreferences:(id)fp8;
- (void)updateThumbnailForProfile:(id)fp8;
- (void)updateThumbnails;
- (void)thumbnailsDidChange;
- (void)delayedSetNeedsDisplay:(BOOL)fp8;
- (void)needsDisplayTimer:(id)fp8;
- (id)thumbnailOfSize:(struct _NSSize)fp8 forProfile:(id)fp16;

@end

@interface TTInspectorController : NSWindowController
{
    NSView *_contentView;
    NSView *_notApplicableView;
    NSTextField *_titleField;
    NSTabView *_tabView;
    NSObjectController *_tabObjectController;
    TTSettingsThumbnailArrayController *_settingsController;
}

+ (id)sharedInspectorController;
- (id)initWithWindow:(id)fp8;
- (void)windowDidLoad;
- (void)windowWillClose:(id)fp8;
- (void)dealloc;
- (void)observeValueForKeyPath:(id)fp8 ofObject:(id)fp12 change:(id)fp16 context:(void *)fp20;
- (BOOL)validateMenuItem:(id)fp8;
- (id)settingsController;
- (void)selectTitleField:(id)fp8;
- (void)setInspectorApplicable:(BOOL)fp8;

@end

@interface TTPopUpButtonCell : NSPopUpButtonCell
{
}

- (struct _NSRect)imageRectForBounds:(struct _NSRect)fp8;
- (BOOL)trackMouse:(id)fp8 inRect:(struct _NSRect)fp12 ofView:(id)fp28 untilMouseUp:(BOOL)fp32;

@end

@interface TTTableView : NSTableView
{
    NSString *_emptyMessage;
}

- (id)emptyMessageAttributes;
- (id)emptyMessage;
- (void)setEmptyMessage:(id)fp8;
- (void)drawRect:(struct _NSRect)fp8;

@end

@interface TTSettingsPickerSourceCell : TTSettingsSourceCell
{
}

- (BOOL)shouldShowDefaultCell;

@end

@interface TTTemporaryProfile : TTProfile
{
    TTTabController *_controller;
}

- (id)objectSpecifier;
- (void)setTabController:(id)fp8;

@end

@interface TTProfile (Scripting)
- (id)objectSpecifier;
- (id)scriptUniqueID;
- (id)scriptNumberOfRows;
- (void)setScriptNumberOfRows:(id)fp8;
- (id)scriptNumberOfColumns;
- (void)setScriptNumberOfColumns:(id)fp8;
- (id)scriptCursorColor;
- (void)setScriptCursorColor:(id)fp8;
- (id)scriptBackgroundColor;
- (void)setScriptBackgroundColor:(id)fp8;
- (id)scriptNormalTextColor;
- (void)setScriptNormalTextColor:(id)fp8;
- (id)scriptBoldTextColor;
- (void)setScriptBoldTextColor:(id)fp8;
- (id)scriptFontName;
- (void)setScriptFontName:(id)fp8;
- (int)scriptFontSize;
- (void)setScriptFontSize:(int)fp8;
- (BOOL)scriptFontAntialiasing;
- (void)setScriptFontAntialiasing:(BOOL)fp8;
- (id)scriptCleanCommands;
- (void)setScriptCleanCommands:(id)fp8;
- (BOOL)scriptTitleDisplaysDeviceName;
- (void)setScriptTitleDisplaysDeviceName:(BOOL)fp8;
- (BOOL)scriptTitleDisplaysShellPath;
- (void)setScriptTitleDisplaysShellPath:(BOOL)fp8;
- (BOOL)scriptTitleDisplaysWindowSize;
- (void)setScriptTitleDisplaysWindowSize:(BOOL)fp8;
- (BOOL)scriptTitleDisplaysSettingsName;
- (void)setScriptTitleDisplaysSettingsName:(BOOL)fp8;
- (BOOL)scriptTitleDisplaysCustomTitle;
- (void)setScriptTitleDisplaysCustomTitle:(BOOL)fp8;
- (id)scriptCustomTitle;
- (void)setScriptCustomTitle:(id)fp8;
@end

@interface TTFakeScrollView : TTAccessibleView
{
    NSScroller *_scroller;
    NSView *_contentView;
}

- (id)initWithFrame:(struct _NSRect)fp8 scroller:(id)fp24 contentView:(id)fp28;
- (void)drawRect:(struct _NSRect)fp8;
- (id)accessibilityAttributeNames;
- (id)ttaxRoleAttribute;
- (BOOL)ttaxIsRoleAttributeMutable;
- (id)ttaxRoleDescriptionAttribute;
- (BOOL)ttaxIsRoleDescriptionAttributeMutable;
- (id)ttaxHorizontalScrollBarAttribute;
- (BOOL)ttaxIsHorizontalScrollBarAttributeMutable;
- (id)ttaxVerticalScrollBarAttribute;
- (BOOL)ttaxIsVerticalScrollBarAttributeMutable;
- (id)ttaxContentsAttribute;
- (BOOL)ttaxIsContentsAttributeMutable;
- (id)ttaxFocusedAttribute;
- (BOOL)ttaxIsFocusedAttributeMutable;
- (void)ttaxSetFocusedAttribute:(id)fp8;

@end

@interface TTProfileMenuItem : NSMenuItem
{
}

+ (BOOL)usesUserKeyEquivalents;

@end

